<!DOCTYPE html>
<html>
<head>
    <title><?= htmlspecialchars($this->config->item('title')) ?></title>
    <meta charset="utf-8" />
    <meta name="viewport" content="initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no"/>

    <!-- jQuery Mobile; on THIS page we want mobile theme no matter what, s we're compatible with both -->
    <script type="text/javascript" src="<?= site_url('static/common/jquery-1.7.2.min.js'); ?>"></script>
    <script type="text/javascript" src="<?= site_url('static/common/jquery.mobile-1.1.0/jquery.mobile-1.1.0.min.js'); ?>"></script>
    <link type="text/css" rel="stylesheet" href="<?= site_url('static/common/jquery.mobile-1.1.0/jquery.mobile-1.1.0.css'); ?>" />

    <style type="text/css">
    </style>
</head>
<body>

<div data-role="page">
    <div data-role="header">
        <h1>Browser Check</h1>
    </div>
    <div data-role="content">
        <ul data-role="listview" data-inset="true">
            <?php foreach ($options as $option) { ?>
            <li><a href="<?= $option['url'] ?>" data-ajax="false"><?= $option['text'] ?></a></li>
            <?php } ?>
        </ul>
    </div>
    <br/>
    <br/>
    <br/>
</div>

</body>
</html>