export const NAV_WIDTH_EXPANDED = 200
export const NAV_WIDTH_COLLAPSED = 76
export const PANEL_WIDTH = 320
export const MOBILE_BOTTOM_BAR_HEIGHT = 76
export const MOBILE_SHEET_EXPANDED_TOP = 72
export const MOBILE_SHEET_PEEK_STRIP_HEIGHT = 52
export const MOBILE_SHEET_PEEKED_HEIGHT = MOBILE_BOTTOM_BAR_HEIGHT + MOBILE_SHEET_PEEK_STRIP_HEIGHT // 128
