<?php $this->page_title = 'Log'; ?>

<p class="lead">System audit log.</p>

<table id="auditlog" class="table table-striped table-condensed">
<thead>
<tr>
    <th>Timestamp</th>
    <th>IP Address</th>
    <th>Username</th>
    <th>Message</th>
</tr>
</thead>
<tbody>
<?php foreach ($logs as $log) { ?>
<tr>
    <td><?= substr($log->timestamp,0,19) ?></td>
    <td><?= $log->ipaddress ?></td>
    <td><?= htmlspecialchars($log->username) ?></td>
    <td><?= htmlspecialchars($log->message) ?></td>
</tr>
<?php } ?>
</tbody>
</table>

<script type="text/javascript">
$(window).load(function() {
    $('#auditlog').tablesorter();
    $('#auditlog').addClass('tablesorter');
});
</script>