<?php $this->page_title = 'Manage Contributors'; ?>

<ul class="local-actions">
    <li><a href="<?= ssl_url('administration/contributor/0/') ?>" class="btn btn-primary">+ New contributor</a></li>
</ul>

<table id="contributors" class="table table-striped">
<thead>
<tr>
  <th>Name &amp; Organization</th>
  <th>E-mail</th>
  <th>Admin</th>
  <th>SWGH</th>
  <th>Markers</th>
  <th>Loops</th>
  <th>Trails</th>
  <th>Hint Maps</th>
  <th>Edit</th>
</tr>
</thead>
<tbody>
<?php foreach ($contributors as $contributor) { ?>
<?php
  $true_markup = '<strong>yes</strong>';
  $false_markup = 'no';
?>
  <tr>
    <td><a href="<?= ssl_url("administration/contributor/{$contributor->id}") ?>"><?= htmlspecialchars($contributor->realname) ?></a></td>
    <td><?= htmlspecialchars($contributor->email) ?></td>
    <td><?= $contributor->admin          == 'f' ? $false_markup : $true_markup ?></td>
    <td><?= $contributor->allow_swgh     == 'f' ? $false_markup : $true_markup ?></td>
    <td><?= $contributor->allow_markers  == 'f' ? $false_markup : $true_markup ?></td>
    <td><?= $contributor->allow_loops    == 'f' ? $false_markup : $true_markup ?></td>
    <td><?= $contributor->allow_trails   == 'f' ? $false_markup : $true_markup ?></td>
    <td><?= $contributor->allow_hintmaps == 'f' ? $false_markup : $true_markup ?></td>
    <td><a href="<?= ssl_url("administration/contributor/{$contributor->id}") ?>">edit</a></td>
  </tr>
<?php } ?>
</tbody>
</table>

<script type="text/javascript">
$(document).ready(function() {
    $('#contributors').tablesorter({
        sortList: [[0,0]]
    });
    $('#contributors').addClass('tablesorter');

});
</script>