<?php $this->page_title = 'Manage Contributors'; ?>

<div style="margin: 2em 0">
  <a href="<?= ssl_url('administration/contributor/0/') ?>" class="btn btn-primary">+ New contributor</a>
</div>

<table id="contributors" class="table table-striped">
<thead>
<tr>
  <th></th>
  <th>Name &amp; Organization</th>
  <th>E-mail</th>
  <th>Admin</th>
  <th>SWGH</th>
  <th>Markers</th>
  <th>Loops</th>
  <th>Closures</th>
</tr>
</thead>
<tbody>
<?php foreach ($contributors as $contributor) { ?>
  <tr>
    <td><a href="<?= ssl_url("administration/contributor/{$contributor->id}") ?>">edit</a></td>
    <td><?= htmlspecialchars($contributor->realname) ?></td>
    <td><?= htmlspecialchars($contributor->email) ?></td>
    <td><?= $contributor->admin          == 'f' ? 'no' : 'yes' ?></td>
    <td><?= $contributor->allow_swgh     == 'f' ? 'no' : 'yes' ?></td>
    <td><?= $contributor->allow_markers  == 'f' ? 'no' : 'yes' ?></td>
    <td><?= $contributor->allow_loops    == 'f' ? 'no' : 'yes' ?></td>
    <td><?= $contributor->allow_closures == 'f' ? 'no' : 'yes' ?></td>
  </tr>
<?php } ?>
</tbody>
</table>

<script type="text/javascript">
$(window).load(function() {
    $('#contributors').tablesorter({
        sortList: [[0,0]]
    });
    $('#contributors').addClass('tablesorter');
});
</script>