<html>
<head>
    <meta charset="utf-8" />
    <title><?= htmlspecialchars($this->config->item('title')) ?> :: Administration</title>

    <!-- jQuery et al -->
    <script type="text/javascript" src="<?= ssl_url('static/common/jquery-1.7.2.min.js'); ?>"></script>
    <script type="text/javascript" src="<?= ssl_url('static/common/jquery-ui-1.8.21.custom.min.js'); ?>"></script>
    <link type="text/css" rel="stylesheet" href="<?= ssl_url('static/common/jquery-ui-lightness/jquery-ui-1.8.20.custom.css'); ?>" />

    <!-- tablesorter -->
    <script type="text/javascript" src="<?= ssl_url('static/common/tablesorter/jquery.tablesorter.js'); ?>"></script>
    <link type="text/css" rel="stylesheet" href="<?= ssl_url('static/common/tablesorter/themes/blue/style.css'); ?>" />

    <!-- Leaflet map interface -->
    <link rel="stylesheet" type="text/css" href="<?= ssl_url('static/common/leaflet3/dist/leaflet.css'); ?>" />
    <!--[if lte IE 8]><link rel="stylesheet" href="<?= ssl_url('static/common/leaflet3/dist/leaflet.ie.css'); ?>" /><![endif]-->
    <script type="text/javascript" src="<?= ssl_url('static/common/leaflet3/dist/leaflet-src.js'); ?>"></script>
    <script type="text/javascript" src="<?= ssl_url('static/common/leaflet-bing.js'); ?>"></script>
    <script type="text/javascript" src="<?= ssl_url('static/common/leaflet-scalebar.js'); ?>"></script>
    <script type="text/javascript" src="<?= ssl_url('static/common/leaflet-wkt.js'); ?>"></script>

    <!-- TinyMCE, the HTML editor -->
    <script type="text/javascript" src="<?= ssl_url('static/tinymce/jscripts/tiny_mce/jquery.tinymce.js'); ?>"></script>

    <!-- our own local javaScript and CSS -->
    <script type="text/javascript" src="<?= ssl_url('static/common/constants.js'); ?>"></script>
    <script type="text/javascript" src="<?= ssl_url('static/admin/admin.js'); ?>"></script>
    <link rel="stylesheet" type="text/css" href="<?= ssl_url('static/admin/admin.css'); ?>" />
</head>
<body>

<div id="navbar">
    <a href="<?= ssl_url('administration/') ?>">Main Menu</a>
    <a href="<?= ssl_url('administration/contributors/') ?>">Contributors</a>
    <a href="<?= ssl_url('administration/markers/') ?>">Markers</a>
    <a href="<?= ssl_url('administration/purge_tilestache') ?>">Purge</a>
    <a href="<?= ssl_url('administration/seed_tilestache') ?>">Seed</a>
    <a href="<?= ssl_url('docs/') ?>">Documentation</a>
    <a href="<?= ssl_url('administration/auditlog/') ?>">Log</a>
    <a href="<?= ssl_url('administration/logout/') ?>">Log Out</a>
</div>
