<?php $this->page_title = isset($hint_map->id) ? 'Edit Hint Map' : 'Create Hint Map'; ?>

<form class="form-horizontal" method="post" action="<?= ssl_url("administration/hint_map_save") ?>" onSubmit="return validateFormEditHintMap()" style="margin-top: 2em;">

<input type="hidden" name="id" value="<?= $hint_map ? $hint_map->id : 0 ?>" />

<div class="form-group">
    <label class="control-label col-sm-2">Title:</label>
    <div class="col-sm-4">
        <input class="form-control" type="text" name="title" maxlength="100" value="<?= $hint_map ? htmlspecialchars($hint_map->title) : '' ?>" />
    </div>
</div>

<?php if (isset($hint_map->id)): ?>

<div class="form-group">
    <label class="control-label col-sm-2">URL Alias:</label>
    <div class="col-sm-4">
        <?php $hint_url = $hint_map ? $hint_map->hint_url(TRUE) : ''; ?>
        <p class="form-control-static"><a href="<?= $hint_url ?>"><?= $hint_url ?></a></p>
    </div>
</div>

<?php endif; ?>

<div class="form-group">
    <label class="control-label col-sm-2">External URL:</label>
    <div class="col-sm-4">
        <input class="form-control" type="text" name="url_external" value="<?= $hint_map ? htmlspecialchars($hint_map->url_external) : '' ?>" />
        <small class="text-muted">Use the <a href="https://www.mapbox.com/studio/styles/cleveland-metroparks/cisvvmgwe00112xlk4jnmrehn/static/" target="_blank">Mapbox Static Image generator</a> to identify a map area (with width:??? and height:???) and copy-paste the generated URL here. The image will be saved locally.</small>
    </div>
</div>

<?php if (isset($hint_map->url_external)): ?>
<div class="form-group">
    <label class="control-label col-sm-2">Remote image:</label>
    <div class="col-sm-4">
        <a href="<?= $hint_map ? $hint_map->url_external : '' ?>" target="_blank">
            <img src="<?= $hint_map ? $hint_map->url_external : '' ?>" alt="" title="<?= $hint_map ? htmlspecialchars($hint_map->title) : '' ?>" height="100" />
        </a>
    </div>
</div>
<?php endif; ?>

<?php if (isset($hint_map->image_filename_local)): ?>

<?php
    if ($hint_map) {
        $local_image_url = ssl_url($this->config->item('hint_maps_dir_rel') . '/' . $hint_map->image_filename_local);
        $local_image_path = $this->config->item('hint_maps_dir') . '/' . $hint_map->image_filename_local;
    } else {
        $local_image_url = '';
        $local_image_path = '';
    }
?>

<div class="form-group">
    <label class="control-label col-sm-2">Cached image:</label>
    <div class="col-sm-4">
        <a href="<?= $local_image_url ?>" target="_blank">
            <img src="<?= $local_image_url ?>" alt="Cached image" title="" height="100" />
        </a>
    </div>
</div>

<div class="form-group">
    <label class="control-label col-sm-2">Cached image path:</label>
    <div class="col-sm-4">
        <pre><?= $local_image_path ?></pre>
    </div>
</div>

<?php endif; ?>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-4">
        <input class="btn btn-primary" type="submit" value="Save" />
        <?php if (isset($hint_map->id)): ?>
            <a class="btn btn-primary" href="/administration/hint_map/<?= $hint_map->id ?>/delete" role="button">Delete</a>
        <?php endif; ?>
    </div>
</div>

</form>


<script type="text/javascript">
    function validateFormEditHintMap() {
        var error = null;
        if (! $('input[name="title"]').val() ) {
            error = "Title field is required.";
        }
        if (error) {
            alert(error);
            return false;
        }
        var formValid = true;
        return formValid;
    }
</script>