<?php $this->page_title = 'User Login'; ?>

<form method="post" action="<?= ssl_current_url() ?>" class="form-login">
    <label for="inputUsername" class="sr-only">Username:</label>
    <input type="text" id="inputUsername" name="username" class="form-control" placeholder="Username" required autofocus />
    <label for="inputPassword" class="sr-only">Password:</label>
    <input type="password" name="password" class="form-control" placeholder="Password" required />
    <button type="submit" value="Log in" class="btn btn-lg btn-primary btn-block">Sign in</button>
</form>