<?php $this->page_title = 'Marker'; ?>

<div class="row" style="margin-top: 2em;">
    <div class="col-md-6">
        <dl class="dl-horizontal">
            <dt>Created by:</dt>
            <dd><a target="_blank" href="<?= ssl_url("administration/contributor/{$marker->creatorid}") ?>"><?= htmlspecialchars($marker->creator) ?></a></dd>

            <dt>Created on:</dt>
            <dd><?= $marker->created ?></dd>

            <?php if ($marker->expires) { ?>
                <dt>Expires:</dt>
                <dd><?= $marker->expires ?></dd>
            <?php } ?>

            <dt>Title:</dt>
            <dd><?= htmlspecialchars($marker->title) ?></dd>

            <dt>Content:</dt>
            <dd><code><?= htmlspecialchars($marker->content) ?></code></dd>
        </dl>
    </div>
</div>

<div class="row">
    <div class="col-md-offset-2 col-md-4">
        <div id="map_canvas" style="width: 100%; height: 3in; border: 1px solid black;"></div>
    </div>
</div>

<div class="row" style="margin-top: 1em;">
    <div class="col-md-6">
        <dl class="dl-horizontal">
            <dt>Lat:</dt>
            <dd><?= $marker->lat ?></dd>

            <dt>Lon:</dt>
            <dd><?= $marker->lng ?></dd>
        </dl>
    </div>
</div>

<script type="text/javascript">
var MARKER;

$(window).load(function () {
    initAdminMap();

    // center the map
    var lat = <?= $marker->lat ?>;
    var lng = <?= $marker->lng ?>;
    var zum = 15;
    MAP.setView(new L.LatLng(lat,lng),zum);

    // add the marker
    MARKER = new L.Marker(new L.LatLng(lat,lng), { clickable:false });
    MAP.addLayer(MARKER);

    // our version of a WMS GetFeatureInfo control: a map click calls query.php to get JSON info, and we construct a bubble
    MAP.on('contextmenu', function (event) {
        var data = {};

        // buffer the click point a little to make a box
        var sw = MAP.layerPointToLatLng(new L.Point(event.layerPoint.x - 10 , event.layerPoint.y - 10));
        var ne = MAP.layerPointToLatLng(new L.Point(event.layerPoint.x + 10 , event.layerPoint.y + 10));
        data.w = sw.lng;
        data.s = sw.lat;
        data.e = ne.lng;
        data.n = ne.lat;
        var anchor = new L.LatLng(event.latlng.lat,event.latlng.lng);

        // add the list of layers
        data.layers = [];
        for (var i=0, l=OVERLAYS.length; i<l; i++) {
            if (OVERLAYS[i].options.visibility) data.layers[data.layers.length] = i;
        }

        // do the AJAX thing
        $.get('../../ajax/adminquery', data, function (html) {
            if (!html) return;
            var popup = new L.Popup();
            popup.setLatLng(anchor);
            popup.setContent(html);
            MAP.openPopup(popup);
        }, 'html');
    });

});
</script>


<form class="form-horizontal" method="post" action="<?= ssl_url("administration/deletemarker/") ?>" onSubmit="return confirm('Really delete this marker?');">
    <input type="hidden" name="id" value="<?= $marker->id ?>" />
    <div class="form-group">
        <div class="col-md-offset-2 col-md-4">
            <input type="submit" value="Delete" class="btn btn-primary" />
        </div>
    </div>
</form>