<table id="markers" style="width:75%;">
<thead>
<tr>
    <th></th>
    <th style="text-align:left; padding-right:2em;">Status</th>
    <th style="text-align:left;">Created</th>
    <th style="text-align:left; padding-right:2em;">Expires</th>
    <th style="text-align:left; padding-right:2em;">Creator</th>
    <th style="text-align:left; padding-right:2em;">Title</th>
    <th style="text-align:left; padding-right:2em;">Content</th>
</tr>
</thead>
<tbody>
<?php foreach ($markers as $marker) { ?>
<tr>
    <td><a href="<?= ssl_url("administration/marker/{$marker->id}") ?>">view</a></td>
    <td><?= $marker->enabled ? 'visible' : '-' ?></td>
    <td><?= $marker->created ?></td>
    <td><?= $marker->expires ?></td>
    <td><?= htmlspecialchars($marker->creator) ?></td>
    <td><?= htmlspecialchars($marker->title) ?></td>
    <td><?= htmlspecialchars(strip_tags(substr($marker->content,0,100))) ?></td>
</tr>
<?php } ?>
</tbody>
</table>




<script type="text/javascript">
$(window).load(function() {
    $('#markers').tablesorter({
        sortList: [[0,0]]
    });
    $('#markers').addClass('tablesorter');
});
</script>