<?php $this->page_title = 'Markers'; ?>

<table id="markers" class="table table-striped">
<thead>
<tr>
    <th></th>
    <th>Status</th>
    <th>Created</th>
    <th>Expires</th>
    <th>Creator</th>
    <th>Title</th>
    <th>Content</th>
</tr>
</thead>
<tbody>
<?php foreach ($markers as $marker) { ?>
<tr>
    <td><a href="<?= ssl_url("administration/marker/{$marker->id}") ?>">view</a></td>
    <td><?= $marker->enabled ? 'visible' : '-' ?></td>
    <td><?= $marker->created ?></td>
    <td><?= $marker->expires ?></td>
    <td><?= htmlspecialchars($marker->creator) ?></td>
    <td><?= htmlspecialchars($marker->title) ?></td>
    <td><?= htmlspecialchars(strip_tags(substr($marker->content,0,100))) ?></td>
</tr>
<?php } ?>
</tbody>
</table>




<script type="text/javascript">
$(window).load(function() {
    $('#markers').tablesorter({
        sortList: [[0,0]]
    });
    $('#markers').addClass('tablesorter');
});
</script>