<?php $this->page_title = 'Purge Tilestache'; ?>

<style>
.progress-updates {
    max-height: 8em;
    overflow: scroll;
    display: none;
}
</style>

<p>Use this tool to empty the TileStache tile cache, after you have made some changes to data which will affect the basemap.</p>

<div class="progress-indicator" id="progress-indicator" style="display: none;">
    <div class="progress">
        <div class="progress-bar progress-bar-striped active" role="progressbar"
            aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width:0%">
        Purging...
        </div>
    </div>
    <h4>Output:</h4>
    <pre class="progress-updates"></pre>
</div>

<form id="purge-tilestache" action="<? ssl_current_url() ?>" method="post">
    <input name="ok" value="Purge TileStache cache" class="btn btn-primary" onclick="startPurge()" />
</form>

<script type="text/javascript">

    /**
     * Start the Tilestache Purge process, with progress indication.
     */
    function startPurge() {
        // Disable "start" button while we do the work
        $('form#purge-tilestache input[name="ok"]').blur().val('Purging...').prop("disabled", true);

        progressActivate('Purging...');
        progressInitialize('', '% Complete');
        progressAddUpdate('Starting tilestache purge...');

        var job_id;

        // Create a system job
        $.ajax({
            type: 'GET',
            url: '../../ajax/create_job',
            async: false,
            data: { title: 'purge_tilestache' },
            success: function(reply) {
                job_id = jQuery.parseJSON(reply);
            },
            error: function (xhr, status, text) {
                console.log('create_job error: ' + text);
            }
        });

        // Start the Purge process
        $.ajax({
            type: 'GET',
            url: '../../ajax/purge_tilestache',
            async: true,
            data: { job_id: job_id },
            success: function(reply) {
                progressIndicateFinished(reply);
            },
            error: function (xhr, status, text) {
                console.log('purge_tilestache error: ' + text);
                console.log(xhr);
            }
        });

        // Check progress of the process and quit when finished
        var progress_checker = setInterval(function() {
            $.get('../../ajax/check_job_progress', { job_id: job_id }, function (response) {
                if (!response) return;

                job_progress = jQuery.parseJSON(response);
                // .status, .percent_complete, .status_msg

                if (job_progress.status_msg !== null) {
                    progressAddUpdate(job_progress.status_msg);
                }
                progressSetPercentFinished(job_progress.percent_complete, '', '% Complete');

                if (job_progress.status == 'COMPLETE'
                        || job_progress.status == 'ABORTED'
                        || job_progress.percent_complete >= 100)  {
                    // Finished...
                    // Stop this checker timer
                    clearInterval(progress_checker);
                    // Re-enable "start" button with new text
                    $('form#purge-tilestache input[name="ok"]').val('Purge again').prop("disabled", false);
                }
            }, 'html');
        }, 500);
    }

</script>