<p>Use this tool to re-populate the TileStache tile cache, after you have purged it. Don't bother doing this if you haven't purged the cache, because it won't re-generate already-existing tiles.</p>
<p>Note that this will take several hours to complete, but there will be a progress monitor.</p>

<form action="<? ssl_current_url() ?>" method="post">
    <input type="submit" name="ok" value="Seed the TileStache cache" />
</form>