<?php $this->page_title = 'Seed TileStache'; ?>

<p>Use this tool to re-populate the TileStache tile cache, after you have <a href="<?= ssl_url("administration/purge_tilestache") ?>">purged it</a>. Don't bother doing this if you haven't <a href="<?= ssl_url("administration/purge_tilestache") ?>">purged the cache</a>, because it won't re-generate already-existing tiles.</p>

<p>Note that this will take several hours to complete, (with progress indication). If seeding is interrupted it can be re-run and will essentially pick up where it left off.</p>

<div class="progress-indicator" id="progress-indicator" style="display: none;">
    <div class="progress">
        <div class="progress-bar progress-bar-striped active" role="progressbar"
            aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width:0%">
        Purging...
        </div>
    </div>
    <h4>Output:</h4>
    <pre class="progress-updates"></pre>
</div>

<form id="seed-tilestache" action="<? ssl_current_url() ?>" method="post">
    <input name="ok" value="Seed TileStache" class="btn btn-primary" onclick="startSeedTilestache()" />
</form>

<script type="text/javascript">

    /**
     * Start the TileStache Seed process, with progress indication.
     */
    function startSeedTilestache() {
        // Disable "start" button while we do the work
        $('form#seed-tilestache input[name="ok"]').blur().val('Purging...').prop("disabled", true);

        progressActivate('Purging...');
        progressInitialize('', '% Complete');
        progressAddUpdate('Starting TileStache seed...');

        var job_id;

        // Create a system job
        $.ajax({
            type: 'GET',
            url: '../../ajax/create_job',
            async: false,
            data: { title: 'seed_tilestache' },
            success: function(reply) {
                job_id = jQuery.parseJSON(reply);
            },
            error: function (xhr, status, text) {
                console.log('create_job error: ' + text);
            }
        });

        // Start the Seed process
        $.ajax({
            type: 'GET',
            url: '../../ajax/seed_tilestache',
            async: true,
            data: { job_id: job_id },
            success: function(reply) {
                progressIndicateFinished(reply);
            },
            error: function (xhr, status, text) {
                console.log('seed_tilestache error: ' + text);
                console.log(xhr);
            }
        });

        // Check progress of the process and quit when finished
        var progress_checker = setInterval(function() {
            $.get('../../ajax/check_job_progress', { job_id: job_id }, function (response) {
                if (!response) return;

                job_progress = jQuery.parseJSON(response);
                // .status, .percent_complete, .status_msg

                if (job_progress.status_msg !== null) {
                    progressAddUpdate(job_progress.status_msg);
                }
                progressSetPercentFinished(job_progress.percent_complete, '', '% Complete');

                if (job_progress.status == 'COMPLETE'
                        || job_progress.status == 'ABORTED'
                        || job_progress.percent_complete >= 100)  {
                    // Finished...
                    // Stop this checker timer
                    clearInterval(progress_checker);
                    // Re-enable "start" button with new text
                    $('form#seed-tilestache input[name="ok"]').val('Seed again').prop("disabled", false);
                }
            }, 'html');
        }, 500);
    }

</script>