<div class="admin_wms_popup admin_query_trail">

<h3>Trail: <?= htmlspecialchars($feature->label_name) ?></h3>
<table>
    <tr><th>paved</th><td><?= $feature->paved ?></td></tr>
    <tr><th>bike</th><td><?= $feature->bike ?></td></tr>
    <tr><th>bridle</th><td><?= $feature->bridle ?></td></tr>
    <tr><th>hike</th><td><?= $feature->hike ?></td></tr>
    <tr><th>difficulty</th><td><?= $feature->skill_cm ?></td></tr>
    <tr><th>length</th><td><?= round($feature->length) ?> ft</td></tr>
</table>

<span class="queryinfo queryinfo_trail" title="<?= htmlspecialchars(trim($feature->label_name)) ?>" lat="<?= $feature->lat ?>" lng="<?= $feature->lng ?>" boxw="<?= $feature->boxw ?>" boxs="<?= $feature->boxs ?>" boxe="<?= $feature->boxe ?>" boxn="<?= $feature->boxn ?>" wkt="<?= $feature->wkt ?>"></span>

</div>

