<?php
	$park_name = htmlspecialchars($feature->pagetitle);

	$main_site_url = 'https://www.clevelandmetroparks.com/';
	if (!empty($feature->pagethumbnail)) {
		$img_src = str_replace('~/', $main_site_url, $feature->pagethumbnail);
		$img_markup = '<img src="' . $img_src .'" alt="' . $img_src . '">';
	} else {
		$img_markup = '';
	}
?>

<h2><?= $park_name ?></h2>

<?= $img_markup ?>

<p><?= $feature->descr ?></p>

<h4>Hours of Operation</h4>
<?= $feature->hoursofoperation ?>

<?php if (!empty($feature->phone)): ?>
	<h4>Phone</h4>
	<?= $feature->phone ?>
<? endif; ?>

<div class="lat_driving"><?= $feature->drivingdestinationlatitude ?></div>
<div class="lng_driving"><?= $feature->drivingdestinationlongitude ?></div>