<div class="wkt"><?= $feature->wkt ?></div>


<?php
$loop = new Loop();
$feature->uses = $loop->useTypesString($feature);
$steps = json_decode($feature->steps);
?>

<h2><?= htmlspecialchars($feature->name) ?></h2>

<?php if ($feature->closed) { ?>
<p class="park-alert">Some portions may be closed to access. Please check the map for more details.</p>
<?php } ?>

<p>
Length: <?= $feature->distancetext ?><br/>
<?php if ($feature->hike   == 'Yes') { ?>Est time<?php if ($feature->bike == 'Yes' or $feature->bridle == 'Yes') { ?>, walking<?php } ?>: <?= $feature->durationtext_hike ?><br/><?php } ?>
<?php if ($feature->bike   == 'Yes') { ?>Est time, bicycle: <?= $feature->durationtext_bike ?><br/><?php } ?>
<?php if ($feature->bridle == 'Yes') { ?>Est time, horseback: <?= $feature->durationtext_bridle ?><br/><?php } ?>
<?php if ($feature->difficulty) { ?>Difficulty: <?= $feature->difficulty ?><br/><?php } ?>
<?php if ($feature->paved) { ?>Paved: <?= $feature->paved ?><br/><?php } ?>
</p>

<p>
    <?= $feature->description ?>
</p>

<ul id="moreinfo_steps" data-role="listview" class="ui-listview">
<?php foreach ($steps as $step) { ?>
    <li class="ui-li ui-li-static ui-body-c">
        <div class="ui-btn-text">
            <span class="ui-li-heading"><?= $step->stepnumber ?>. <?= $step->text ?></span>
            <span class="ui-li-desc">Go <?= $step->distance ?></span>
            <?php if ($feature->hike   == 'Yes') { ?><span class="ui-li-desc"><?php if ($feature->bike == 'Yes' or $feature->bridle == 'Yes') { ?>Walking:<?php } ?> <?= $step->timehike ?></span><?php } ?>
            <?php if ($feature->bike   == 'Yes') { ?><span class="ui-li-desc">Bicycle: <?= $step->timebike ?></span><?php } ?>
            <?php if ($feature->bridle == 'Yes') { ?><span class="ui-li-desc">Horseback: <?= $step->timebridle ?></span><?php } ?>
        </div>
    </li>
<?php } ?>
</ul>


<?php if ($feature->closed) { ?>
<p class="alert">Some portions may be closed to access. Please check the map for more details.</p>
<?php } ?>

<div class="elevationprofileimage" style="text-align:center;">
    <img src="<?= site_url("static/images/loops/{$feature->id}.jpg") ?>" />
</div>

<br/>
