<h2><?= htmlspecialchars($feature->pagetitle) ?></h2>

<?php if (isset($activities)): ?>
	<h4>Activities:</h4>
	<ul class="activities-icon-list">
	<?php
		$activity_icons_dir = '/static/images/activities/';
        foreach ($activities as $activity) {
            $icon_url = site_url($activity_icons_dir . $activity->icon);
            $activity_title = htmlspecialchars($activity->pagetitle);
            print '<li><img src="' . $icon_url . '" title="' . $activity_title . '" class="" /></li>';
        }
	?>
	</ul>
<?php endif; ?>

<?php if ($feature->descr): ?>
	<div><?= nl2br($feature->descr) ?></div>
<?php endif; ?>

<ul class="nobull">
	<?php if ($feature->cmp_url): ?>
		<li><a href="<?= $feature->cmp_url ?>" target="_blank">More Info</a></li>
	<?php endif; ?>
</ul>

<h4>GPS coordinates:</h4>
<div class="small-light">
	<?= $feature->latitude ?><br/>
	<?= $feature->longitude ?>
</div>