<h2><?= htmlspecialchars($feature->use_area) ?></h2>

<?php if ($feature->activity): ?>
	<h4>Activities:</h4>
	<div><?= htmlspecialchars($feature->activity) ?></div>
<?php endif; ?>

<?php if ($feature->description): ?>
	<div><?= nl2br($feature->description) ?></div>
<?php endif; ?>

<ul class="nobull">
	<?php if ($feature->link): ?>
		<li><a href="<?= $feature->link ?>" target="_blank">More Info</a></li>
	<?php endif; ?>
	
	<?php if ($feature->cal_link): ?>
		<li><a href="<?= $feature->cal_link ?>" target="_blank">Reservations &amp; Events Calendar</a></li>
	<?php endif; ?>
	
	<?php if ($feature->image_url): ?>
		<li><span class="fakelink paddme" onClick="showPhoto('<?= $feature->image_url ?>');">Photo</span></li>
	<?php endif; ?>
</ul>

<h4>GPS coordinates:</h4>
<div class="small-light">
	<?= $feature->lat_dms ?><br/>
	<?= $feature->lng_dms ?>
</div>