<h2><?= htmlspecialchars($feature->use_area) ?></h2>

<?php if ($feature->activity): ?>
	<h4>Activities:</h4>
	<div><?= htmlspecialchars($feature->activity) ?></div>
	<div style="height: 1em;"></div>
<?php endif; ?>


<?php if ($feature->description): ?>
	<div>
	<?php
		$this->load->helper('misc');
		$description = _strip_description_markup(nl2br($feature->description));
		print $description;
	?>
	</div>
	<div style="height: 1em;"></div>
<?php endif; ?>


<h4>GPS coordinates:</h4>
<div class="small-light">
	<?= $feature->lat_dms ?><br/>
	<?= $feature->lng_dms ?>
</div>