<h2><?= htmlspecialchars($feature->pagetitle) ?></h2>

<?php if (isset($activities)): ?>
	<h4>Activities:</h4>
	<ul class="activities-icon-list">
	<?php
		$activity_icons_dir = '/static/images/activities/';
        foreach ($activities as $activity) {
            if ($activity->icon) {
                $icon_url = site_url($activity_icons_dir . $activity->icon);
                $activity_title = htmlspecialchars($activity->pagetitle);
                print '<li><img src="' . $icon_url . '" title="' . $activity_title . '" alt="' . $activity_title . '" /></li>';
            }
        }
	?>
	</ul>
<?php endif; ?>

<?php if ($feature->descr): ?>
	<div class="feature-description"><?= nl2br($feature->descr) ?></div>
<?php endif; ?>

<?php //if ($feature->cmp_url): ?>
<?php if (false): ?>
	<ul class="nobull">
		<li><a href="<?= $this->config->item('main_site_url') . ltrim($feature->cmp_url, '/') ?>" target="_blank">More Info</a></li>
	</ul>
<?php endif; ?>

<h4>GPS coordinates:</h4>
<div class="small-light">
	<?= $feature->latitude ?><br/>
	<?= $feature->longitude ?>
</div>