<?php
	$park_name = htmlspecialchars($feature->pagetitle);

	$max_img_width = '320';

	if (!empty($feature->pagethumbnail)) {
		$this->load->helper('misc');
		$img_url = _transform_main_site_image_url($feature->pagethumbnail, $max_img_width);
		$img_markup = '<img src="' . $img_url .'" alt="' . $park_name . '">';
	} else {
		$img_markup = '';
	}
?>

<h2><?= $park_name ?></h2>

<?= $img_markup ?>

<p><?= $feature->descr ?></p>

<h4>Hours of Operation</h4>
<?= $feature->hoursofoperation ?>

<?php if (!empty($feature->phone)): ?>
	<h4>Phone</h4>
	<a title="Call <?= $park_name ?>" href="tel:<?= $feature->phone ?>"><?= $feature->phone ?></a>
<? endif; ?>

<div class="lat_driving"><?= $feature->drivingdestinationlatitude ?></div>
<div class="lng_driving"><?= $feature->drivingdestinationlongitude ?></div>