<div class="query_poi">
<h3 class="popup_title"><?= htmlspecialchars($feature->use_area) ?></h3>
<span class="fakelink zoom" type="poi" title="<?= htmlspecialchars(trim($feature->use_area)) ?>" gid="<?= $feature->gid ?>" lat="<?= $feature->lat ?>" lng="<?= $feature->lng ?>" lat_driving="<?= $feature->lat_driving ?>" lng_driving="<?= $feature->lng_driving ?>" w="<?= $feature->boxw ?>" s="<?= $feature->boxs ?>" e="<?= $feature->boxe ?>" n="<?= $feature->boxn ?>" onClick="zoomElementClick( $(this) );">Details</span>
</div>