<div class="query_trailpiece">
<!--
The trail returned by a click-query is in fact a Trailpiece object, not a Trail.
This template is called if the Trailpiece does not have any Trail objects associated to it, so thie segment really is all there is to know.
-->
<h3 class="popup_title"><?= htmlspecialchars(trim($feature->label_name)) ?></h3>
<p style="margin-top:0;">
    <?= $feature->pri_use ?><?php if ($feature->paved) { ?>, <?= $feature->paved == 'Yes' ? 'Paved' : 'Unpaved' ?><?php } ?>
    <br/>
    Uses: <?= Trailpiece::getUsesString($feature) ?>
    <br/>
    <br/>
    Elevation <?= $feature->elevation ?> feet
</p>

<!--
<p style="color:#E0E0E0;">GID: <?= $feature->gid ?><br/></p>
-->

<span class="fakelink zoom" type="trailpiece" title="<?= htmlspecialchars(trim($feature->label_name)) ?>" lat="<?= $feature->lat ?>" lng="<?= $feature->lng ?>" w="<?= $feature->boxw ?>" s="<?= $feature->boxs ?>" e="<?= $feature->boxe ?>" n="<?= $feature->boxn ?>" wkt="<?= $feature->wkt ?>" onClick="zoomElementClick( $(this) );">Directions here</span>
</div>