<div class="query_reservation">
<h3 class="popup_title"><?= htmlspecialchars(trim($feature->res)) ?></h3>
<span class="fakelink zoom" type="reservation" title="<?= htmlspecialchars(trim($feature->res)) ?>" gid="<?= $feature->gid ?>" lat="<?= $feature->lat ?>" lng="<?= $feature->lng ?>" w="<?= $feature->boxw ?>" s="<?= $feature->boxs ?>" e="<?= $feature->boxe ?>" n="<?= $feature->boxn ?>" onClick="zoomElementClick( $(this) );">Details</span>
</div>