<div class="query_trail">
<!--
The trail returned by a click-query is in fact a Trailpiece object, not a Trail.
This template is called if the Trailpiece has one or more Trail objects associated to it, whole Trails as opposed to the single segment.
It shows the segment's own name, then info on the parent Trails
-->

<!-- the Trailpiece info: elevation and a Directions Here link -->
<p>
    <h3 class="popup_title"><?= htmlspecialchars(trim($feature->label_name)) ?></h3>
    Elevation <?= $feature->elevation ?> feet
    <br/>
    <span class="fakelink zoom" type="trailpiece" title="<?= htmlspecialchars(trim($feature->label_name)) ?>" lat="<?= $feature->lat ?>" lng="<?= $feature->lng ?>" w="<?= $feature->boxw ?>" s="<?= $feature->boxs ?>" e="<?= $feature->boxe ?>" n="<?= $feature->boxn ?>" wkt="<?= $feature->wkt ?>" onClick="zoomElementClick( $(this) );">Directions here</span>
</p>


<?php foreach ($moreinfo as $trail) { ?>
    <h4 class="popup_title"><?= htmlspecialchars($trail->name) ?></h4>
    <p style="margin-top:0;">
        Primary use: <?= $trail->pri_use ?><br/>
        Uses: <?= $trail->uses ?><br/>
        Paved: <?= $trail->paved ?><br/>
        Total length: <?= $trail->length_text ?>
        <br/>
        <span class="fakelink zoom" type="trail" title="<?= htmlspecialchars($trail->name) ?>" gid="<?= $trail->gid ?>" lat="<?= $trail->lat ?>" lng="<?= $trail->lng ?>" lat_driving="<?= $trail->lat_driving ?>" lng_driving="<?= $trail->lng_driving ?>" w="<?= $trail->boxw ?>" s="<?= $trail->boxs ?>" e="<?= $trail->boxe ?>" n="<?= $trail->boxn ?>" onClick="zoomElementClick( $(this) );">More Info</span>
    </p>
<?php } ?>

</div>