<div class="query_reservation">
<h3 class="popup_title"><?= htmlspecialchars(trim($feature->res)) ?></h3>

    <div class="links">
        <span class="fakelink zoom" type="reservation" title="<?= htmlspecialchars(trim($feature->res)) ?>" gid="<?= $feature->gid ?>" lat="<?= $feature->lat ?>" lng="<?= $feature->lng ?>" w="<?= $feature->boxw ?>" s="<?= $feature->boxs ?>" e="<?= $feature->boxe ?>" n="<?= $feature->boxn ?>" onClick="SKIP_TO_DIRECTIONS=false; zoomElementClick( $(this) );">Details</span>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <span class="fakelink zoom" type="reservation" title="<?= htmlspecialchars(trim($feature->res)) ?>" gid="<?= $feature->gid ?>" lat="<?= $feature->lat ?>" lng="<?= $feature->lng ?>" w="<?= $feature->boxw ?>" s="<?= $feature->boxs ?>" e="<?= $feature->boxe ?>" n="<?= $feature->boxn ?>" onClick="SKIP_TO_DIRECTIONS=true; zoomElementClick( $(this) );">Directions</span>
    </div>
</div>