<div class="query_building">
<h3 class="popup_title"><?= htmlspecialchars(trim($feature->name)) ?></h3>
<span class="fakelink zoom" type="building" title="<?= htmlspecialchars(trim($feature->name)) ?>" gid="<?= $feature->gid ?>" lat="<?= $feature->lat ?>" lng="<?= $feature->lng ?>" lat_driving="<?= $feature->lat_driving ?>" lng_driving="<?= $feature->lng_driving ?>" w="<?= $feature->boxw ?>" s="<?= $feature->boxs ?>" e="<?= $feature->boxe ?>" n="<?= $feature->boxn ?>" onClick="zoomElementClick( $(this) );">Details</span>
</div>