<!-- Linked from Welcome pane -->
<div class="sidebar-pane" id="pane-amenities">
    <h1 class="sidebar-header">
        <span class="title-text">Amenities</span>
        <span class="sidebar-close"><i class="cm-icon cm-icon-caret-left"></i></span>
    </h1>

    <a href="#pane-welcome" class="sidebar-pane-link sidebar-back ui-btn ui-btn-inline ui-icon-back ui-btn-icon-left ui-corner-all">Back</a>

    <ul data-role="listview" data-inset="true">
    <?php foreach ($amenities as $id => $amenity) { ?>
        <li>
            <a href="<?= "#browse-results?amenity_id=$id" ?>">
                <i class="cm-icon cm-icon-<?= $amenity['icon'] ?>"></i>
                <?= htmlspecialchars($amenity['title']) ?>
            </a>
        </li>
    <?php } ?>
    </ul>
</div>