<!-- Linked from Find pane -->
<div class="sidebar-pane" id="pane-browse-pois-activity">
    <h1 class="sidebar-header">
        <span class="title-text">Find POIs</span>
        <span class="sidebar-close"><i class="cm-icon cm-icon-caret-left"></i></span>
    </h1>

    <a href="#pane-browse" class="sidebar-pane-link sidebar-back ui-btn ui-btn-inline ui-icon-back ui-btn-icon-left ui-corner-all">Back</a>
    
    <ul data-role="listview" data-inset="true">
    <?php $activity_icons_dir = '/static/images/activities/'; ?>
        <?php foreach ($activities as $activity_id => $activity) { ?>
            <?php
                $link_param_category = 'pois_usetype_' . urlencode($activity['title']);
                $link_url = "#browse-results?id=${activity_id}&category=${link_param_category}";
                $icon_url = site_url($activity_icons_dir . $activity['icon']);
            ?>
            <li>
                <a href="<?= $link_url ?>">
                    <img class="ui-li-icon" src="<?= $icon_url ?>" /> <?= htmlspecialchars($activity['title']) ?>
                </a>
            </li>
        <?php } ?>
    </ul>
</div>