<div class="sidebar-pane" id="pane-browse">
    <h1 class="sidebar-header">
        Find<span class="sidebar-close"><i class="fa fa-caret-left"></i></span>
    </h1>

    <fieldset data=role="controlgroup">
        <b>Keyword search:</b>
        <input type="text" data-mini="true" id="browse_keyword" />
        <ul id="browse_keyword_autocomplete" data-role="listview" data-inset="true"></ul>
        <input type="button" data-mini="true" id="browse_keyword_button" value="Search &gt;&gt;" />
    </fieldset>

    <ul data-role="listview" data-inset="true">
        <li><a href="#pane-browse-pois-activity" class="sidebar-pane-link">
            <i class="fa fa-map-marker"></i>
            Points of Interest</a>
        </li>
        <li><a href="#pane-trailfinder" class="sidebar-pane-link">
            <i class="fa fa-map-signs"></i>
            Trail Finder</a>
        </li>
        <li><a href="#pane-loops-search" class="sidebar-pane-link">
            <i class="fa fa-star"></i>
            Featured Routes</a>
        </li>
    </ul>
</div>