<div class="sidebar-pane" id="pane-browse">
    <h1 class="sidebar-header">
        <span class="title-text">Find</span>
        <span class="sidebar-close"><i class="cm-icon cm-icon-caret-left"></i></span>
    </h1>

    <fieldset data=role="controlgroup">
        <h4>Keyword search:</h4>
        <input type="text" data-mini="true" id="browse_keyword" />
        <ul id="browse_keyword_autocomplete" data-role="listview" data-inset="true"></ul>
        <input type="button" data-mini="true" id="browse_keyword_button" value="Search &raquo;" />
    </fieldset>

    <ul class="browse-main" data-role="listview" data-inset="true">
        <li><a href="#pane-activities" class="sidebar-pane-link">
            <i class="cm-icon cm-icon-map-marker"></i>
            Activities</a>
        </li>
        <li><a href="#pane-trails" class="sidebar-pane-link">
            <i class="cm-icon cm-icon-map-signs"></i>
            Trails</a>
        </li>
    </ul>
</div>