<div class="sidebar-pane" id="pane-credits">
    <h1 class="sidebar-header">
        <span class="title-text">Credits</span>
        <span class="sidebar-close"><i class="cm-icon cm-icon-caret-left"></i></span>
    </h1>

    <p>Parks and facilities data by:<br />
        <a target="_blank" href="https://clevelandmetroparks.com/">Cleveland Metroparks</a></p>
    <p>Some base map data:<br />
        &copy; <a target="_blank" href="http://www.openstreetmap.org/copyright">OpenStreetMap contributors</a></p>
    <p>Driving and transit directions courtesy of:<br />
        <a target="_blank" href="http://www.bing.com/maps/">Bing Maps</a></p>
    <p>Map interface developed by:<br />
        <a target="_blank" href="https://www.websubstrate.com/">Substrate Websoft</a> and <a target="_blank" href="http://www.greeninfo.org/">GreenInfo Network</a></p>

    <h4>Disclaimer</h4>

    <p class="disclaimer">This information is for display purposes only. Cleveland Metroparks makes no warranties, expressed or implied, with respect to the accuracy of and the use of this map and mapping application for any specific purpose. Cleveland Metroparks expressly disclaims any liability that may result from the use of this map or mapping application. For more information, please contact: Stephen Mather, GIS Manager, 4101 Fulton Pkwy, Cleveland, Ohio 44144 (216) 635-3243</p>
</div>