<div class="sidebar-pane" id="pane-directions">
    <h1 class="sidebar-header">
        <span class="title-text">Get Directions</span>
        <span class="sidebar-close"><i class="cm-icon cm-icon-caret-left"></i></span>
    </h1>

    <fieldset data-role="controlgroup">
        <h4>From:</h4>
        <input type="text" id="source-input" class="feature-search-input" placeholder="Park feature or address" />
        <ul id="source-autocomplete" data-role="listview" data-inset="true" data-filter="true" data-input="#source-input" data-value-sourcetarget="source" class="feature-search-autocomplete ui-listview ui-listview-inset ui-corner-all ui-shadow">
            <li class="ui-li-static ui-body-inherit ui-screen-hidden">
                <div class="ui-loader">
                    <span class="ui-icon ui-icon-loading"></span>
                </div>
            </li>
        </ul>
    </fieldset>

    <fieldset data-role="controlgroup">
        <h4>To:</h4>
        <input type="text" id="target-input" class="feature-search-input" placeholder="Park feature or address" />
        <ul id="target-autocomplete" data-role="listview" data-inset="true" data-filter="true" data-input="#target-input" data-value-sourcetarget="target" class="feature-search-autocomplete ui-listview ui-listview-inset ui-corner-all ui-shadow" data-filter-reveal="true">
            <li class="ui-li-static ui-body-inherit ui-screen-hidden">
                <div class="ui-loader">
                    <span class="ui-icon ui-icon-loading"></span>
                </div>
            </li>
        </ul>
    </fieldset>

    <div id="directions-via" class="via-buttons" data-value="hike">
        <a href="#" class="ui-btn ui-btn-inline ui-corner-all via-hike active" data-value="hike" title="On foot">
            <i class="cm-icon cm-icon-walk" aria-hidden="true"></i>
        </a>
        <a href="#" class="ui-btn ui-btn-inline ui-corner-all via-bike" data-value="bike" title="By Bicycle">
            <i class="cm-icon cm-icon-bicycle" aria-hidden="true"></i>
        </a>
        <a href="#" class="ui-btn ui-btn-inline ui-corner-all via-car" data-value="car" title="By car">
            <i class="cm-icon cm-icon-car" aria-hidden="true"></i>
        </a>
        <a href="#" class="ui-btn ui-btn-inline ui-corner-all via-bus" data-value="bus" title="Via public transit">
            <i class="cm-icon cm-icon-bus" aria-hidden="true"></i>
        </a>
    </div>

    <fieldset data-role="controlgroup">
        <input type="button" id="get-directions" value="Get directions" />
    </fieldset>

    <ul id="directions-steps" data-role="listview"></ul>

</div>