<!-- Triggered via JS, by clicking "Elevation Profile" in Directions -->
<div class="sidebar-pane" id="pane-elevationprofile">
    <h1 class="sidebar-header">
        <span class="title-text">Elevation</span>
        <span class="sidebar-close"><i class="cm-icon cm-icon-caret-left"></i></span>
    </h1>

    <a href="#pane-directions" class="sidebar-pane-link sidebar-back ui-btn ui-btn-inline ui-icon-back ui-btn-icon-left ui-corner-all">Back</a>

    <canvas id="elevation-profile"></canvas>
</div>