<!-- Triggered via JS: showElevation() -->
<div class="sidebar-pane" id="pane-elevationprofile">
    <h1 class="sidebar-header">
        Elevation<span class="sidebar-close"><i class="fa fa-caret-left"></i></span>
    </h1>
    <a href="#pane-getdirections" class="sidebar-pane-link">Back</a>
    <div class="elevationprofileimage" style="text-align:center;">
       <img id="elevation" src="about:blank" />
    </div>
</div>