<!-- Triggered via JS: showElevation() -->
<div class="sidebar-pane" id="pane-elevationprofile">
    <h1 class="sidebar-header">
        <span class="title-text">Elevation</span>
        <span class="sidebar-close"><i class="fa fa-caret-left"></i></span>
    </h1>

    <a href="#pane-getdirections" class="sidebar-pane-link sidebar-back ui-btn ui-btn-inline ui-icon-back ui-btn-icon-left ui-corner-all">Back</a>

    <div class="elevationprofileimage" style="text-align:center;">
       <img id="elevation" src="about:blank" />
    </div>
</div>