<div class="sidebar-pane" id="pane-getdirections">
    <h1 class="sidebar-header">
        <span class="title-text">Get Directions</span>
        <span class="sidebar-close"><i class="fa fa-caret-left"></i></span>
    </h1>

    <input type="hidden" id="directions_source_lat" value="" />
    <input type="hidden" id="directions_source_lng" value="" />
    <input type="hidden" id="directions_source_type" value="" />
    <input type="hidden" id="directions_source_gid"  value="" />
    <input type="hidden" id="directions_target_lat" value="" />
    <input type="hidden" id="directions_target_lng" value="" />
    <input type="hidden" id="directions_target_type" value="" />
    <input type="hidden" id="directions_target_gid"  value="" />

    <div id="getdirections_disabled">
        Please select a destination.
        <br/>
        <input type="button" id="change_directions_target2" value="Select a destination" />
    </div>

    <div id="getdirections_enabled" style="display:none;">
        <div id="change_directions_target">
            <a href="#pane-browse" class="sidebar-pane-link">change<br/>destination</a>
        </div>

        <fieldset data=role="controlgroup">
            <select id="directions_reverse" data-mini="true">
            <option value="to">Get directions to</option>
            <option value="from">Get directions from</option>
            </select>
            <br/>

            <div id="directions_target_title"></div>
            <br/>

            <select id="directions_type" data-mini="true">
            <option value="gps">from your current location</option>
            <option value="geocode">from a street address</option>
            <option value="features">from a park feature or point of interest</option>
            </select>

            <div id="directions_type_geocode_wrap" style="display:none;">
                <input type="text" data-mini="true" id="directions_address" placeholder="enter address or place name" />
            </div>

            <select id="directions_via" data-mini="true"><!-- if the default changes, may need to change the via supplements below -->
            <option value="bike">By bicycle</option>
            <option value="car" selected="true">By car</option>
            <option value="hike">By foot</option>
            <!--<option value="bridle">By horse</option>-->
            <option value="bus">By public transportation</option>
            </select>

            <span id="directions_via_bike_wrap" style="display:none;"><!-- hide because Car is default -->
                <select id="directions_via_bike" data-mini="true">
                <option value="bike_advanced">Advanced</option>
                <option value="bike_intermediate">Intermediate</option>
                <option value="bike_beginner">Beginner</option>
                <option value="bike_novice">Novice</option>
                </select>
            </span>

            <select id="directions_prefer" data-mini="true">
                <option value="recommended" selected="true">Recommended route</option>
                <option value="shortest">Shortest route</option>
                <!--<option value="fastest">Fastest route</option>-->
            </select>
    
            <span id="directions_button_wrapper">
                <input type="button" data-mini="true" id="directions_button" value="Get directions" value0="Loading" value1="Get directions" />
            </span>
        </fieldset>
        <br/>
        <ul id="directions_steps" data-role="listview"></ul>
    </div>
</div>