<!-- Triggered via JS: When clicking on map points -->
<div class="sidebar-pane" id="pane-info">
    <h1 class="sidebar-header">
        <span class="title-text">Info</span>
        <span class="sidebar-close"><i class="fa fa-caret-left"></i></span>
    </h1>

    <a href="#pane-map" class="sidebar-pane-link sidebar-back ui-btn ui-btn-inline ui-icon-back ui-btn-icon-left ui-corner-all">Back</a>
    
    <div id="info-content"></div>

    <a class="ui-btn ui-btn-inline ui-icon-location ui-btn-icon-left ui-corner-all" id="show_on_map">Show on Map</a>
    
    <div class="info-directions">
        <h4>Get directions:</h4>
        <div>
            <a href="" class="ui-btn ui-btn-inline ui-corner-all" id="directions_hike" title="Get directions via hiking trails">
                <i class="fa fa-blind" aria-hidden="true"></i>
            </a>
            <a href="" class="ui-btn ui-btn-inline ui-corner-all" id="directions_bike" title="Get directions via bicycle trails">
                <i class="fa fa-bicycle" aria-hidden="true"></i>
            </a>
            <a href="" class="ui-btn ui-btn-inline ui-corner-all" id="directions_car" title="Get driving directions">
                <i class="fa fa-bus" aria-hidden="true"></i>
            </a>
            <a href="" class="ui-btn ui-btn-inline ui-corner-all" id="directions_bus" title="Get directions via public transit">
                <i class="fa fa-car" aria-hidden="true"></i>
            </a>
        </div>
    </div>
</div>