<div class="sidebar-pane" id="pane-legend">

    <h1 class="sidebar-header">
        <span class="title-text">Trail & Route Legend</span>
        <span class="sidebar-close"><i class="cm-icon cm-icon-caret-left"></i></span>
    </h1>

    <ul class="map-legend">
        <li>
            <img src="/static/images/legend/legend-all_purpose.gif" width="56" height="56" alt="All Purpose Trail icon" />
            <span class="info">
                <h4>All Purpose Trail</h4>
            </span>
        </li>
        <li>
            <img src="/static/images/legend/legend-towpath.gif" width="56" height="56" alt="Towpath Trail icon" />
            <span class="info">
                <h4>Towpath Trail</h4>
                <p>* On-road portions are dashed</p>
            </span>
        </li>
        <li>
            <img src="/static/images/legend/legend-lakefront_bikeway.gif" width="56" height="56" alt="Cleveland Lakefront Bikeway icon" />
            <span class="info">
                <h4>Cleveland Lakefront Bikeway</h4>
                <p>* On-road portions are dashed</p>
            </span>
        </li>
        <li>
            <img src="/static/images/legend/legend-bridle.gif" width="56" height="56" alt="Bridle Trail icon" />
            <span class="info">
                <h4>Bridle Trail</h4>
            </span>
        </li>
        <li>
            <img src="/static/images/legend/legend-hiking.gif" width="56" height="56" alt="Hiking Trail icon" />
            <span class="info">
                <h4>Hiking Trail</h4>
            </span>
        </li>
        <li>
            <img src="/static/images/legend/legend-mtb.gif" width="56" height="56" alt="Mountain Bike Trail icon" />
            <span class="info">
                <h4>Mountain Bike Trail</h4>
            </span>
        </li>
        <li>
            <img src="/static/images/legend/legend-walkway.gif" width="56" height="56" alt="Walkway icon" />
            <span class="info">
                <h4>Walkway</h4>
            </span>
        </li>
    </ul>

    <div class="map-legend-bt">
        <h3>Buckeye Trail</h3>
        <p>* Displayed along trail or road it follows</p>
        <ul>
            <li><img src="/static/images/legend/legend-bt1.gif" width="56" height="56" alt="Buckeye Trail icon" /></li>
            <li><img src="/static/images/legend/legend-bt2.gif" width="56" height="56" alt="Buckeye Trail icon" /></li>
            <li><img src="/static/images/legend/legend-bt3.gif" width="56" height="56" alt="Buckeye Trail icon" /></li>
            <li><img src="/static/images/legend/legend-bt4.gif" width="56" height="56" alt="Buckeye Trail icon" /></li>
        </ul>
    </div>

</div>