<!-- Triggered via JS: showPhoto() -->
<div class="sidebar-pane" id="pane-photo">
    <h1 class="sidebar-header">
        <span class="title-text">Photo</span>
        <span class="sidebar-close"><i class="fa fa-caret-left"></i></span>
    </h1>
    <a href="#pane-info" class="sidebar-pane-link sidebar-back ui-btn ui-btn-inline ui-icon-back ui-btn-icon-left ui-corner-all">Back</a>
    <h1>Photo</h1>
    <div style="text-align:center;">
       <img id="photo" src="about:blank" />
    </div>
</div>