<div class="sidebar-pane" id="pane-print">

    <h1 class="sidebar-header">
        <span class="title-text">Find</span>
        <span class="sidebar-close"><i class="fa fa-caret-left"></i></span>
    </h1>

    <a href="#pane-browse" class="sidebar-pane-link sidebar-back ui-btn ui-btn-inline ui-icon-back ui-btn-icon-left ui-corner-all">Back</a>

    <fieldset data=role="controlgroup">
        <b>Comment or note:</b>
        <input type="text" data-mini="true" id="print_comment" value="A title for your map" maxlength="100" />

        <b>Paper size:</b>
        <select id="print_paper" data-mini="true">
            <option value="Letter portrait">8&frac12;x11 Portrait</option>
            <option value="Letter landscape">8&frac12;x11 Landscape</option>
            <option value="Ledger portrait">11x17 Portrait</option>
            <option value="Ledger landscape">11x17 Landscape</option>
        </select>

        <input type="button" id="print_button" value="Create PDF" onClick="printMap();" />
    </fieldset>

    <div id="print_waiting">
        <img src="<?= site_url('static/common/spinner.gif') ?>" />
        <br/>
        One moment please
    </div>

    <div id="print_ready">
        Your map is ready.
        <br/>
        <a id="print_link" target="_blank" href="">Click here to download</a>
    </div>
</div>