<div class="sidebar-pane" id="pane-radar">
    <h1 class="sidebar-header">
        <span class="title-text">Nearby</span>
        <span class="sidebar-close"><i class="cm-icon cm-icon-caret-left"></i></span>
    </h1>

    <label><input type="checkbox" id="radar_enabled" /> Enable alerts</label>

    <br />

    <div id="radar_config" style="display:none;">
        <strong>Alert me when I am within:</strong>
        <select id="radar_radius">
            <option value="6.10">20 feet</option>
            <option value="15.24">50 feet</option>
            <option value="30.48">100 feet</option>
            <option value="76.2">250 feet</option>
            <option value="152.4" selected="true">500 feet</option>
            <option value="402.336">&frac14; mile</option>
            <option value="804.672">&frac12; mile</option>
            <option value="1207.08">&frac34; mile</option>
            <option value="1609.344">1 mile</option>
        </select>

        <br />

        <strong>Watch for these types of features:</strong>
        <fieldset data-role="controlgroup">
            <?php foreach ($poicategories as $category) { ?>
                <label><input type="checkbox" name="radar_category" value="<?= htmlspecialchars($category) ?>"><?= htmlspecialchars($category) ?></label>
            <?php } ?>
        </fieldset>
    </div>

    <br/>

    <ul id="alerts" data-role="listview"></ul>

</div>