<!-- Triggered via JS: On clicking Search button -->
<div class="sidebar-pane" id="pane-search">
    <h1 class="sidebar-header">
        <span class="title-text">Search</span>
        <span class="sidebar-close"><i class="cm-icon cm-icon-caret-left"></i></span>
    </h1>

    <a href="#pane-browse" class="sidebar-pane-link sidebar-back ui-btn ui-btn-inline ui-icon-back ui-btn-icon-left ui-corner-all">Back</a>

    <fieldset data-role="controlgroup">
        <h4>Keyword search</h4>

        <form class="ui-filterable autocomplete">
            <input type="text" id="search_keyword" data-type="search" />
            <input type="button" id="search_keyword_button" value="Search &raquo;" value0="Loading" value1="Search &raquo;" />
        </form>

        <ul id="search_keyword_autocomplete" data-role="listview" data-inset="true" data-filter="true"  data-input="#search_keyword" data-filter-reveal="true"></ul>
    </fieldset>
    
    <br/>
    
    <div class="sortpicker">
        <span class="fakelink" value="distance">Sort by distance away</span>
        &bull;
        <span class="fakelink" value="alphabetical">Sort alphabetically</span>
        <br/>
        <br/>
    </div>
    
    <ul id="keyword_results" data-role="listview" class="distance_sortable"></ul>
</div>