<div class="sidebar-pane" id="pane-settings">
    <h1 class="sidebar-header">
        Settings<span class="sidebar-close"><i class="fa fa-caret-left"></i></span>
    </h1>

    <h3>Map Type</h3>
    <fieldset data-role="controlgroup">
        <label><input type="radio" name="basemap" value="map" checked="true" />Map</label>
        <label><input type="radio" name="basemap" value="photo" />Satellite</label>
    </fieldset>
    
    <h3>GPS Location</h3>
    <div class="fakeinput" id="gps_location" style="text-align:center;">N 00 00.000 W 000 00.000</div>
    
    <h3>Other Settings</h3>
    <label><input type="checkbox" id="settings_show_welcome" />Show the Welcome panel</label>
    <br/>
    
    <div style="text-align:center;">
        <br/>
        <a href="#pane-credits" class="sidebar-pane-link">About this app</a>
    </div>
</div>