<div class="sidebar-pane" id="pane-settings">
    <h1 class="sidebar-header">
        <span class="title-text">Settings</span>
        <span class="sidebar-close"><i class="cm-icon cm-icon-caret-left"></i></span>
    </h1>

    <label for="map_type">Map type</label>
    <fieldset id="map_type" data-role="controlgroup">
        <label><input type="radio" name="basemap" value="map" checked="true" />Default</label>
        <label><input type="radio" name="basemap" value="photo" />Satellite</label>
    </fieldset>

    <label for="coordinate_format">Coordinate format</label>
    <fieldset id="coordinate_format" data-role="controlgroup">
        <label><input type="radio" name="coordinate_format" value="dms" checked="true" />Degrees Minutes Seconds</label>
        <label><input type="radio" name="coordinate_format" value="ddm" />Degrees Decimal Minutes</label>
        <label><input type="radio" name="coordinate_format" value="dd" />Decimal Degrees</label>
    </fieldset>
    
    <label for="gps_location">Your location</label>
    <div data-role="controlgroup" data-type="horizontal">
        <input type="text" class="js-url-field" value="unknown" id="gps_location" data-wrapper-class="controlgroup-textinput ui-btn" readonly="" style="text-align:center;" value="Enable geolocation" />
        <a href="#" title="Copy to clipboard" alt="Copy" data-copy-id="gps_location" class="ui-btn ui-btn-inline ui-corner-all copy-to-clipboard">
            <i class="cm-icon cm-icon-clipboard"></i>
        </a>
    </div>
</div>