<div class="sidebar-pane" id="pane-share">
    <h1 class="sidebar-header">
        Share Your Map<span class="sidebar-close"><i class="fa fa-caret-left"></i></span>
    </h1>

    <div>
        <div class="fakeinput" id="share_url"></div>
    </div>
    <br/>
    <div class="share_button">
        <a target="_blank" href="javascript:void(0);" id="share_facebook"><img src="<?= site_url('static/mobile/share_facebook.png') ?>" /> Share on Facebook</a>
    </div>
    <div class="share_button">
        <a target="_blank" href="javascript:void(0);" id="share_twitter"><img src="<?= site_url('static/mobile/share_twitter.png') ?>" /> Share on Twitter</a>
    </div>
</div>