<div class="sidebar-pane" id="pane-share">
    <h1 class="sidebar-header">
        <span class="title-text">Share Your Map</span>
        <span class="sidebar-close"><i class="cm-icon cm-icon-caret-left"></i></span>
    </h1>

    <label for="share_url">Share URL</label>
    <div data-role="controlgroup" data-type="horizontal">
        <input type="text" class="js-url-field" value="" id="share_url" data-wrapper-class="controlgroup-textinput ui-btn" readonly="" />
        <a href="#" title="Copy to clipboard" alt="Copy" data-copy-id="share_url" class="ui-btn ui-btn-inline ui-corner-all copy-to-clipboard">
            <i class="cm-icon cm-icon-clipboard"></i>
        </a>
    </div>

    <div class="share_button">
        <a target="_blank" href="javascript:void(0);" id="share_facebook">
            <i class="cm-icon cm-icon-facebook-square"></i>Share on Facebook</a>
    </div>

    <div class="share_button">
        <a target="_blank" href="javascript:void(0);" id="share_twitter">
            <i class="cm-icon cm-icon-twitter-square"></i>Share on Twitter</a>
    </div>

</div>