<!-- Linked from Find pane -->
<div class="sidebar-pane" id="pane-trails">
    <h1 class="sidebar-header">
        <span class="title-text">Trails</span>
        <span class="sidebar-close"><i class="cm-icon cm-icon-caret-left"></i></span>
    </h1>

    <a href="#pane-browse" class="sidebar-pane-link sidebar-back ui-btn ui-btn-inline ui-icon-back ui-btn-icon-left ui-corner-all">Back</a>
    
    <fieldset data=role="controlgroup">
    
    <h4 class="label">Filter by Activity:</h4>
    <!-- Hidden form controls connected to clickable image buttons -->
    <div style="display:none;">
        <select id="loops_filter_type">
        <!-- <option value="">All trail types</option> -->
        <option value="hike">Hiking / Walking</option>
        <option value="bike_Novice">Bicycle, Novice</option>
        <option value="bike_Beginner">Bicycle, Beginner</option>
        <option value="bike_Intermediate">Bicycle, Intermediate</option>
        <option value="bike_Advanced">Bicycle, Advanced</option>
        <option value="bridle">Equestrian</option>
        <option value="exercise">Exercise Trail</option>
        <option value="mountainbike">Mountain Biking Trail</option>
        </select>
    </div>
    <div id="loops_typeicons">
        <img alt="Hiking/Walking" data-value="hike" src="<?= site_url('static/images/activities/hike.svg') ?>" />
        <img alt="Bicycling" data-value="bike_Advanced" src="<?= site_url('static/images/activities/bike.svg') ?>" />
        <img alt="Equestrian" data-value="bridle" src="<?= site_url('static/images/activities/horse.svg') ?>" />
        <!--<img data-value="exercise" src="<?= site_url('static/images/activities/fitness.svg') ?>" />-->
        <img alt="Mountain Biking" data-value="mountainbike" src="<?= site_url('static/images/activities/mtnbike.svg') ?>" />
    </div>
    
    <div style="display:none;">
        <select id="loops_filter_paved">
            <option value="">Paved or unpaved</option>
            <option value="Yes">Paved</option>
            <option value="No">Unpaved</option>
        </select>
    </div>

    <h4 class="label">Filter by Reservation:</h4>
    <select id="loops_filter_reservation">
        <option value="">(any reservation)</option>
        <?php foreach ($reservations as $res) { ?>
        <option value="<?= htmlspecialchars($res->res) ?>"><?= htmlspecialchars($res->res) ?></option>
        <?php } ?>
    </select>

    <h4 class="label">Filter by Route Length:</h4>
    <!-- Hidden form controls connected to clickable buttons -->
    <div data-role="fieldcontain" style="display:none;">
        <b>Length</b>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <span id="loops_filter_distance_min_text"></span> - <span id="loops_filter_distance_max_text"></span>
        <br/>
        Min: <input type="range" id="loops_filter_distance_min" min="0" max="100" value="0" />
        <br/>
        Max: <input type="range" id="loops_filter_distance_max" min="0" max="50" value="50" />
    </div>
    <div id="loops_filter_distancepicker">
        <a href="#" data-min="0" data-max="2">0-2 mi</a>
        <a href="#" data-min="2" data-max="5">2-5 mi</a>
        <a href="#" data-min="5" data-max="10">5-10 mi</a>
        <a href="#" data-min="10" data-max="100">10+ mi</a>
    </div>
    
    <div data-role="fieldcontain" id="loops_filter_duration" style="display:none;">
        <b>Duration</b>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <span id="loops_filter_duration_min_text"></span> - <span id="loops_filter_duration_max_text"></span>
        <br/>
        Min: <input type="range" id="loops_filter_duration_min" min="0" max="300" value="0" />
        <br/>
        Max: <input type="range" id="loops_filter_duration_max" min="0" max="300" value="300" />
    </div>

    </fieldset>

    <div class="sortpicker">
        <span class="fakelink" value="distance">Sort by distance away</span>
        &bull;
        <span class="fakelink" value="alphabetical">Sort alphabetically</span>
        <br/>
    </div>
    
    <ul id="loops_list" data-role="listview" data-inset="true" class="distance_sortable"></ul>
</div>