<div class="sidebar-pane" id="pane-welcome">
    <h1 class="sidebar-header">
        <span class="title-text">Welcome!</span>
        <span class="sidebar-close"><i class="cm-icon cm-icon-caret-left"></i></span>
    </h1>

    <ul>
    <li>Visit
        <ul>
            <li>Amenities</li>
        </ul></li>
    <li>Programs &amp; Events
    <li>Nearby
    <li>Trails
        <ul>
            <li>Trail Finder</li>
            <li>Featured Trails</li>
        </ul></li>
    </ul>

</div>