<div class="sidebar-pane" id="pane-welcome">
    <h1 class="sidebar-header">
        <span class="title-text">Welcome!</span>
        <span class="sidebar-close"><i class="cm-icon cm-icon-caret-left"></i></span>
    </h1>

    <div class="ui-grid-a image-link-grid">
        <div class="ui-block-a welcome-pane-parks">
            <a href="#pane-credits" class="sidebar-pane-link">
                <div class="ui-bar"><span class="link-text">Parks</span></div>
            </a>
        </div>
        <div class="ui-block-b welcome-pane-activities">
            <a href="#pane-browse-pois-activity" class="sidebar-pane-link">
                <div class="ui-bar"><span class="link-text">Activities</span></div>
            </a>
        </div>
        <div class="ui-block-a welcome-pane-visitorcenters">
            <a href="#pane-credits" class="sidebar-pane-link">
                <div class="ui-bar"><span class="link-text">Visitor Centers</span></div>
            </a>
        </div>
        <div class="ui-block-b welcome-pane-amenities">
            <a href="#pane-credits" class="sidebar-pane-link">
                <div class="ui-bar"><span class="link-text">Amenities</span></div>
            </a>
        </div>
        <div class="ui-block-a welcome-pane-trails">
            <a href="#pane-loops-search" class="sidebar-pane-link">
                <div class="ui-bar"><span class="link-text">Trails</span></div>
            </a>
        </div>
        <div class="ui-block-b welcome-pane-events">
            <a href="#pane-credits" class="sidebar-pane-link">
                <div class="ui-bar"><span class="link-text">Events</span></div>
            </a>
        </div>
    </div>

</div>