<?php $this->page_title = 'Autoloop Generator'; ?>


<div class="form-group">
    <label>Base name for the loop:</label>
    <input class="form-control" type="text" name="basename" value="Random" />
</div>

<div class="form-group">
    <label>WP0 lat:</label>
    <input class="form-control" type="text" name="lat" value="<?= $this->config->item('geo_lat') ?>" />
</div>

<div class="form-group">
    <label>WP0 lon:</label>
    <input class="form-control" type="text" name="lon" value="<?= $this->config->item('geo_lon') ?>" />
</div>

<div class="form-group">
    <label>Desired route length:</label>
    <select class="form-control" name="miles">
        <option value="3">3 miles</option>
        <option value="5">5 miles</option>
        <option value="10">10 miles</option>
        <option value="15">15 miles</option>
        <option value="20">20 miles</option>
    </select>
</div>

<div class="form-group">
    <label>Use type:</label>
    <select class="form-control" name="usetype">
        <option value="hike">Hiking trails</option>
        <option value="bike">Bicycle trails</option>
        <option value="bike_novice">Bicycle trails, novice</option>
        <option value="bike_beginner">Bicycle trails &amp; roads, beginner</option>
        <option value="bike_intermediate">Bicycle trails &amp; roads, intermediate</option>
        <option value="bike_advanced">Bicycle trails &amp; roads, advanced</option>
        <option value="bridle">Equestrian trails</option>
    </select>
</div>

<input class="btn btn-primary" type="submit" value="Generate" id="go" />


<script type="text/javascript">
var MY_CONTRIBUTOR_ID = <?= $this->loggedin['id'] ?>;

$(window).load(function () {
    $('#go').click(function () {
        var params = {
            lat      : parseFloat($('input[name="lat"]').val()),
            lon      : parseFloat($('input[name="lon"]').val()),
            miles    : $('select[name="miles"]').val(),
            usetype  : $('select[name="usetype"]').val(),
            basename : $('input[name="basename"]').val(),
            creatorid: MY_CONTRIBUTOR_ID
        };
        if (!params.lat || !params.lon || !params.miles || !params.usetype) return false;

        $.get('../ajax/autoloop', params, function (reply) {
            var loopid = parseInt(reply);
            if (!loopid) return alert(reply);
            document.location.href = '/contributors/loop/' + loopid;
        });

        return false;
    });
});
</script>