<?php $this->page_title = 'Autoloop CSV'; ?>

<p>Upload a CSV file containing the coordinates of trailheads, and let Autoloop generate loops for you. For each point listed, loops will be generated at various (approximated) lengths and for each trail use type (hike, bridle, advanced bike).</p>

<div class="well">
    <h4>CSV Format</h4>
    <ul>
        <li>The CSV file must have 3 columns, ordered: <em>Name, Lat, Lon</em>.</li>
        <li>There must be no header/title row. The very first row is a name &amp; coordinates line.</li>
    </ul>
</div>

<form class="" method="POST" action="<?= ssl_current_url() ?>" enctype="multipart/form-data" id="upload">

<div class="col-sm-6">

<fieldset class="form-group">
    <label class="control-label">Upload CSV:</label>
    <input class="form-control" type="file" name="csv" size="75"/>
</fieldset>

<input type="submit" value="Upload" class="btn btn-primary" />

</div>

</form>


<script type="text/javascript">
$(window).load(function () {
    $('#upload').submit(function () {
        var error = null;
        if (! $('input[type="file"][name="csv"]').val() ) error = "Select a CSV file to upload.";
        if (error) {
            alert(error);
            return false;
        }
        return true;
    });
});
</script>
