<?php $this->page_title = 'Contributor Login'; ?>

<form method="post" action="<?= ssl_current_url() ?>" class="form-login">
    <label for="inputEmail" class="sr-only">Email:</label>
    <input type="email" id="inputEmail" name="username" class="form-control" placeholder="Email" required autofocus />
    <label for="inputPassword" class="sr-only">Password:</label>
    <input type="password" name="password" class="form-control" placeholder="Password" required />
    <button type="submit" value="Log in" class="btn btn-lg btn-primary btn-block">Sign in</button>
</form>