<?php $this->page_title = 'Edit Loop'; ?>


<style type="text/css">
#map_canvas {
    width:5in; height:5in;
}

th,td {
    vertical-align:top;
}

th {
    text-align:left;
    font-size:15pt;
    margin-top:1em;
}

input[readonly="readonly"] {
    background-color: #eee;
}

input.shortversion {
    text-align:right;
    width:0.6in;
}

input.longversion {
    text-align:right;
    width:1.0in;
}

input[name="stepnumber[]"]     { text-align:right; width:0.25in; }
input[name="text[]"]           { text-align:right; width:2.25in; }
input[name="distance[]"]       { text-align:right; width:0.50in; }
input[name="timehike[]"]       { text-align:right; width:0.50in; }
input[name="timebike[]"]       { text-align:right; width:0.50in; }
input[name="timebridle[]"]     { text-align:right; width:0.50in; }

</style>





<script type="text/javascript">
var DIRECTIONS_LINE       = null;
var DIRECTIONS_LINE_STYLE = { color:"#0000FF", weight:5, opacity:0.80, clickable:false };
var ROUGHCUT_LINE         = null;
var ROUGHCUT_LINE_STYLE   = { color: "#FFFFFF", weight:5, opacity:0.5, clickable:false };

var MARKERS = { 'wp0':null, 'wp1':null, 'wp2':null, 'wp3':null, 'wp4':null, 'wp5':null, 'wp6':null, 'wp7':null, 'wp8':null, 'wp9':null };
var ICONS = {
    'wp0' : L.icon({ iconUrl: '<?= ssl_url("static/contributors/wp0.png") ?>', iconSize:[20,34], iconAnchor:[10,34] }),
    'wp1' : L.icon({ iconUrl: '<?= ssl_url("static/contributors/wp1.png") ?>', iconSize:[20,34], iconAnchor:[10,34] }),
    'wp2' : L.icon({ iconUrl: '<?= ssl_url("static/contributors/wp2.png") ?>', iconSize:[20,34], iconAnchor:[10,34] }),
    'wp3' : L.icon({ iconUrl: '<?= ssl_url("static/contributors/wp3.png") ?>', iconSize:[20,34], iconAnchor:[10,34] }),
    'wp4' : L.icon({ iconUrl: '<?= ssl_url("static/contributors/wp4.png") ?>', iconSize:[20,34], iconAnchor:[10,34] }),
    'wp5' : L.icon({ iconUrl: '<?= ssl_url("static/contributors/wp5.png") ?>', iconSize:[20,34], iconAnchor:[10,34] }),
    'wp6' : L.icon({ iconUrl: '<?= ssl_url("static/contributors/wp6.png") ?>', iconSize:[20,34], iconAnchor:[10,34] }),
    'wp7' : L.icon({ iconUrl: '<?= ssl_url("static/contributors/wp7.png") ?>', iconSize:[20,34], iconAnchor:[10,34] }),
    'wp8' : L.icon({ iconUrl: '<?= ssl_url("static/contributors/wp8.png") ?>', iconSize:[20,34], iconAnchor:[10,34] }),
    'wp9' : L.icon({ iconUrl: '<?= ssl_url("static/contributors/wp9.png") ?>', iconSize:[20,34], iconAnchor:[10,34] })
};




$(window).load(function () {

/////
///// load the map, bare bones with layers but not much else
/////
initContributorMap();

// our version of a WMS GetFeatureInfo control: a map click calls query.php to get JSON info, and we construct a bubble
MAP.on('contextmenu', function (event) {

    var data = {};

    // buffer the click point a little to make a box
    var sw = MAP.layerPointToLatLng(new L.Point(event.layerPoint.x - 15 , event.layerPoint.y - 15));
    var ne = MAP.layerPointToLatLng(new L.Point(event.layerPoint.x + 15 , event.layerPoint.y + 15));
    data.w = sw.lng;
    data.s = sw.lat;
    data.e = ne.lng;
    data.n = ne.lat;
    data.zoom = MAP.getZoom();
    var anchor = new L.LatLng(event.latlng.lat,event.latlng.lng);

    // do the AJAX thing
    $.get('../../ajax/query', data, function (html) {
        if (!html) return;
        var popup = new L.Popup();
        popup.setLatLng(anchor);
        popup.setContent(html);
        MAP.openPopup(popup);
    }, 'html');
});



/////
///// enable TinyMCE on the description editor
/////
$('textarea[name="description"]').tinymce({
    // Location of TinyMCE script
    script_url : '<?= ssl_url('static/tinymce/jscripts/tiny_mce/tiny_mce.js') ?>',

    // General options
    theme : "advanced",
    plugins : "autolink,lists,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,advlist",

    // Theme options
    theme_advanced_buttons1 : "cut,copy,paste,pastetext,pasteword,|,search,replace,|,undo,redo,|,hr,removeformat,|,charmap,emotions,media",
    theme_advanced_buttons2 : "code,|,bold,italic,underline,strikethrough,sub,sup,|,formatselect,fontselect,fontsizeselect",
    theme_advanced_buttons3 : "justifyleft,justifycenter,justifyright,justifyfull,|,bullist,numlist,|,outdent,indent,blockquote,|,link,unlink,anchor,image,|,forecolor,backcolor",
    theme_advanced_buttons4 : "tablecontrols",
    theme_advanced_toolbar_location : "top",
    theme_advanced_toolbar_align : "left",
    theme_advanced_statusbar_location : "bottom",
    theme_advanced_resizing : true,

    // Example content CSS (should be your site CSS)
    content_css : "css/content.css",

    // Drop lists for link/image/media/template dialogs
    template_external_list_url : "lists/template_list.js",
    external_link_list_url : "lists/link_list.js",
    external_image_list_url : "lists/image_list.js",
    media_external_list_url : "lists/media_list.js"
});



/////
///// enable the widgets for startdate and expiration date
/////

$('input[name="expires"]').datepicker({
    dateFormat: 'yy-mm-dd'
});

$('#expires_never').click(function () {
    $('input[name="expires"]').val('');
});

$('input[name="startdate"]').datepicker({
    dateFormat: 'yy-mm-dd'
});

$('#startdate_today').click(function () {
    var today = new Date().yyyymmdd();
    $('input[name="startdate"]').val(today);
});


/////
///// enable various buttons and clicks
/////

// geocode submit button
$('#geocode_button').click(function () {
    var address = $('#geocode_text').val();
    geocodeAndZoomContributorMap(MAP, address);
});

// waypoint Add button; pick the map's center, create a marker, populate the text fields, make rough route calculation
$('.wpadd').click(function () {
    var row    = $(this).closest('tr');
    var wpid   = row.prop('id');

    // the marker will load from the text fields; if the fields currently have no value, use the map center
    var lat = parseFloat( row.find('input.lat').val() );
    var lng = parseFloat( row.find('input.lng').val() );
    if (!lat || !lng) {
        var center = MAP.getCenter();
        row.find('input.lat').val(center.lat);
        row.find('input.lng').val(center.lng);
    }

    // add the marker, and its drag handler to update the text box
    if (! MARKERS[wpid]) {
        var lat    = parseFloat( row.find('input.lat').val() );
        var lng    = parseFloat( row.find('input.lng').val() );
        var center = new L.LatLng(lat,lng);
        var icon   = ICONS[wpid];

        MARKERS[wpid] = new L.Marker(center, { clickable:true, draggable:true, icon:icon });
        MARKERS[wpid].wpid = wpid;
        MAP.addLayer(MARKERS[wpid]);

        MARKERS[wpid].on('dragend', function (event) {
            var latlng = this.getLatLng();
            $('#' + this.wpid).find('input.lat').val(latlng.lat);
            $('#' + this.wpid).find('input.lng').val(latlng.lng);
            generateRoughCut();
        });
    }

    // recalculate the rough cut
    generateRoughCut();

    // hide this button, show the opposite
    $(this).hide();
    $(this).siblings('.wpremove').show();
});

// waypoint Remove button; remove the marker, clear the text fields, make rough route calculation
$('.wpremove').click(function () {
    var row  = $(this).closest('tr');
    var wpid = row.prop('id');

    // clear the text fields
    row.find('input.lat').val(0);
    row.find('input.lng').val(0);

    // remove the marker
    if (MARKERS[wpid]) {
        MAP.removeLayer(MARKERS[wpid]);
        MARKERS[wpid] = null;
    }

    // recalculate the rough cut
    generateRoughCut();

    // hide this button, show the opposite
    $(this).hide();
    $(this).siblings('.wpadd').show();
});

// Recalculate button: fetches a route from the server, overwreites MULTILINESTRING, draws it onto the map
$('#recalculate_button').click(function () {
    // load up a list of the waypoints, really a pair of lists: lat,lat,lat & lng,lng,lng
    var lats = [];
    var lngs = [];
    $('#waypoints tr.waypoint').each(function () {
        var lat = parseFloat( $(this).find('input.lat').val() );
        var lng = parseFloat( $(this).find('input.lng').val() );
        if (lat && lng) {
            lats[lats.length] = lat;
            lngs[lngs.length] = lng;
        }
    });

    // a quick check: must be at least 2 waypoints
    if (lats.length < 2 || lngs.length < 2) return alert("Need at least 2 points.");

    // if chosen, close up the loop by adding the first WP as the last WP
    var closed = parseInt( $('[name="closedloop"]').val() );
    if (closed) {
        lats[lats.length] = lats[0];
        lngs[lngs.length] = lngs[0];
    }

    // visual effects: remove the plotted route
    if (DIRECTIONS_LINE) MAP.removeLayer(DIRECTIONS_LINE);

    // visual effects: empty the steps/directions list
    $('#directions').empty();

    // visual effects: disable the button
    var button = $(this);
    button.val( button.attr('value0') );
    button.attr("disabled", "disabled");

    // visual effects: blank the elevation profile picture
    $('#elevation_profile').prop('src','<?= ssl_url('static/common/blank.png') ?>');

    // visual effects: blank the totals
    $('input[name="distance_feet"]').val('');
    $('input[name="distancetext"]').val('');
    $('input[name="duration_hike"]').val('');
    $('input[name="durationtext_hike"]').val('');
    $('input[name="duration_bike"]').val('');
    $('input[name="durationtext_bike"]').val('');
    $('input[name="duration_bridle"]').val('');
    $('input[name="durationtext_bridle"]').val('');
    $('input[name="hike"]').val('');
    $('input[name="bike"]').val('');
    $('input[name="bridle"]').val('');
    $('input[name="difficulty"]').val('');
    $('input[name="paved"]').val('');

    // GET from the server a route covering these waypoints
    var params = {};
    params.lats           = lats.join(",");
    params.lngs           = lngs.join(",");
    params.terrain_filter = $('select[name="terrain_filter"]').val();
    params.trim_spurs     = $('select[name="trim_spurs"]').val();
    $.get('../../ajax/routewaypoints', params, function (reply) {
        // re-enable the button
        button.val( button.attr('value1') );
        button.removeAttr("disabled");

        // warn the user of any problems, pass it on to next-stage handling
        // in this case, an error is not fatal and we continue anyway if we have WKT representing at least a partial route
        if (reply.error) alert(reply.error);
        if (! reply.wkt) return;
        renderRoute(reply);
    }, 'json');
});


// random loop generator
$('#random_button').click(function () {
    // fetch Waypoint 0 and bail if it's not set
    var wp0lat = parseFloat( $('#wp0 input.lat').val() );
    var wp0lng = parseFloat( $('#wp0 input.lng').val() );
    if (! wp0lat || ! wp0lng ) return alert("Pan and center the map and place Waypoint 0 to define your start.");

    // clear the existing waypoints
    $('.wpremove:visible').click();

    // visual effects: disable the button
    var button = $(this);
    button.val( button.attr('value0') );
    button.attr("disabled", "disabled");

    // get the center and radius, GET them to the server
    var center = MAP.getCenter();
    var miles  = $('#random_miles').val();
    var closed = parseInt( $('[name="closedloop"]').val() );
    var filter = $('select[name="terrain_filter"]').val();
    var params = { lat:wp0lat, lng:wp0lng, miles:miles, closed:closed, filter:filter };
    $.get('../../ajax/randomwaypoints', params, function (reply) {
        // re-enable the button
        button.val( button.attr('value1') );
        button.removeAttr("disabled");

        if (! reply.length) return alert(reply);

        // the return is an array of waypoint objects: WP#, lat, lng
        // load them into the corresponding WP boxes
        for (var i=0, l=reply.length; i<l; i++) {
            var div = $('#wp' + reply[i].wp );
            div.find('input.lat').val( reply[i].lat );
            div.find('input.lng').val( reply[i].lng );
            div.find('.wpadd').click();
        }
    }, 'json');
});


/////
///// if there's a loop, a technique for loading the existing loop into the waypoint boxes and the map
///// if not, simply hide the 'remove' buttons because there's nothing yet and we're already done
/////
// phase 1: lay down markers for any waypoints that are populated
$('#waypoints tr.waypoint').each(function () {
    // the waypoint's lat/lng are already loaded into the text fields
    var lat = parseFloat( $(this).find('input.lat').val() );
    var lng = parseFloat( $(this).find('input.lng').val() );

    // click either the Add or Remove button; their actions will show/hide markers, show/hide buttons, et cetera
    if (lat && lng) {
        $(this).find('.wpadd').click();
    } else {
        $(this).find('.wpremove').click();
    }
});
// phase 2: zoom to the collected extent of the markers
{
    var extent = [];
    for (var wpid in MARKERS) {
        if (MARKERS[wpid]) extent[extent.length] = MARKERS[wpid].getLatLng();
    }
    if (extent.length) MAP.fitBounds( new L.LatLngBounds(extent) );
}
// phase 3: load the saved geometry (if any), the rough cut (marker-to-marker segments), and the elevation profile
generateRoughCut();
var wkt = $('input[name="wkt"]').val();
if (wkt) renderWKTtoMap(wkt);
//var elev = $('input[name="elevation_profile"]').val();
//if (elev) renderElevationProfile(elev);
// phase 4: load the directions
renderDirections(<?= $loop ? $loop->steps : '' ?>);

// end of window.load callback
});

function generateRoughCut() {
    if (ROUGHCUT_LINE) {
        MAP.removeLayer(ROUGHCUT_LINE);
        ROUGHCUT_LINE = null;
    }

    var latlngs = [];
    $('#waypoints tr.waypoint').each(function () {
        var lat = parseFloat( $(this).find('input.lat').val() );
        var lng = parseFloat( $(this).find('input.lng').val() );
        if (lat && lng) latlngs[latlngs.length] = new L.LatLng(lat,lng);
    });

    if (latlngs.length >= 2) {
        ROUGHCUT_LINE = new L.MultiPolyline([latlngs], ROUGHCUT_LINE_STYLE);
        MAP.addLayer(ROUGHCUT_LINE);
    }
}

function renderRoute(routestruct) {
    // load the attributes and totals into the text boxes
    $('input[name="distance_feet"]').val(routestruct.totals.distance_feet);
    $('input[name="distancetext"]').val(routestruct.totals.distancetext);
    $('input[name="duration_hike"]').val(routestruct.totals.duration_hike);
    $('input[name="duration_bike"]').val(routestruct.totals.duration_bike);
    $('input[name="duration_bridle"]').val(routestruct.totals.duration_bridle);
    $('input[name="durationtext_hike"]').val(routestruct.totals.durationtext_hike);
    $('input[name="durationtext_bike"]').val(routestruct.totals.durationtext_bike);
    $('input[name="durationtext_bridle"]').val(routestruct.totals.durationtext_bridle);
    $('input[name="hike"]').val(routestruct.use_hike);
    $('input[name="bike"]').val(routestruct.use_bike);
    $('input[name="bridle"]').val(routestruct.use_bridle);
    $('input[name="mountainbike"]').val(routestruct.use_mountainbike);
    $('input[name="difficulty"]').val(routestruct.difficulty);
    $('input[name="paved"]').val(routestruct.paved);

    // parse the bbox and zoom to it
    var bbox = WSENtoBounds(routestruct.bounds.west,routestruct.bounds.south,routestruct.bounds.east,routestruct.bounds.north);
    MAP.fitBounds(bbox);

    // save the WKT to the hidden textarea, then render the represented geometry to map
    $('input[name="wkt"]').val(routestruct.wkt);
    renderWKTtoMap(routestruct.wkt);

    // save the elevation profile in serialized form to the form, so it can be saved to the server later
    var elev = [];
    for (var vi=0, vl=routestruct.elevationprofile.length; vi<vl; vi++) {
        var vpoint = routestruct.elevationprofile[vi];
        elev[elev.length] = vpoint.x + ' ' + vpoint.y;
    }
    elev = elev.join(",");
    $('input[name="elevation_profile"]').val(elev);
    renderElevationProfile(elev);

    // load the directions into a set of text fields
    renderDirections(routestruct.steps);
}


function renderWKTtoMap(wkt) {
    // remove the existing route line from the map
    if (DIRECTIONS_LINE) { MAP.removeLayer(DIRECTIONS_LINE); DIRECTIONS_LINE = null; }

    // parse the WKT to get a new line, add the new line to the map
    var parser = new Wkt.Wkt();
    parser.read(wkt);
    DIRECTIONS_LINE = parser.toObject(DIRECTIONS_LINE_STYLE);
    MAP.addLayer(DIRECTIONS_LINE);
}

function renderElevationProfile(vpoints) {
    // the vertices have horizontal and vertical info (feet and elev). make a pair of arrays
    var x = [];
    var y = [];
    vpoints = vpoints.split(",");
    for (var i=0, l=vpoints.length; i<l; i++) {
        var xy = vpoints[i].split(" ");
        x[x.length] = xy[0];
        y[y.length] = xy[1];
    }
    x = x.join(',');
    y = y.join(',');

    $('#elevation_profile').prop('src','<?= ssl_url('static/common/blank.png') ?>');
    $.post('../../ajax/elevationprofilebysegments', { 'x':x, 'y':y }, function (url) {
        if (url.indexOf('http') != 0) return alert(url);
        $('#elevation_profile').prop('src',url);
        $('input[name="elevation_profile_image"]').val(url);
    });
}

function renderDirections(steps) {
    if (! steps) return;

    var target = $('#directions');
    target.empty();

    for (var i=0, l=steps.length; i<l; i++) {
        var step = steps[i];
        //console.log(step);
        var row = $('<tr></tr>');
        row.append($('<td></td>').append( $('<input></input>').prop('type','text').attr('readonly','readonly').prop('name','stepnumber[]').val(step.stepnumber) ));
        row.append($('<td></td>').append( $('<input></input>').prop('type','text').attr('readonly','readonly').prop('name','text[]').val(step.text) ));
        row.append($('<td></td>').append( $('<input></input>').prop('type','text').attr('readonly','readonly').prop('name','distance[]').val(step.distance) ));
        row.append($('<td></td>').append( $('<input></input>').prop('type','text').attr('readonly','readonly').prop('name','timehike[]').val(step.timehike) ));
        row.append($('<td></td>').append( $('<input></input>').prop('type','text').attr('readonly','readonly').prop('name','timebike[]').val(step.timebike) ));
        row.append($('<td></td>').append( $('<input></input>').prop('type','text').attr('readonly','readonly').prop('name','timebridle[]').val(step.timebridle) ));
        target.append(row);
    }
}
</script>


<form id="loopform" method="post" action="<?= ssl_url("contributors/saveloop/") ?>">
<input type="hidden" name="id" value="<?= $loop ? $loop->id : 0 ?>" />
<input type="hidden" name="wkt" value="<?= $loop ? $loop->wkt : '' ?>" />
<input type="hidden" name="elevation_profile" value="<?= $loop ? $loop->elevation_profile : '' ?>" />
<input type="hidden" name="elevation_profile_image" value="<?= $loop ? ssl_url("static/photos/loops/{$loop->id}.jpg") : '' ?>" />

<table>
<tr>
    <th>Basic Information</th>
    <th>Directions</th>
</tr>
<tr>
    <td>
        <table>
        <tr>
            <td>Name:</td>
            <td><input class="form-control" type="text" name="name" maxlength="200" value="<?= $loop ? htmlspecialchars($loop->name) : '- Untitled Loop' ?>" /></td>
        </tr>
        <tr>
            <td>Description:</td>
            <td><textarea class="form-control" name="description" style="height:5em"><?= $loop ? htmlspecialchars($loop->description) : '' ?></textarea></td>
        </tr>
        <tr>
            <td>Publication</td>
            <td>
                <select class="form-control" name="status">
                    <option <?= $loop ? ($loop->status=='New' ? 'selected="true"' : '') : '' ?> value="New">New</option>
                    <option <?= $loop ? ($loop->status=='In Progress' ? 'selected="true"' : '') : '' ?> value="In Progress">In Progress</option>
                    <?php if ($this->loggedin['admin']) { ?>
                    <option <?= $loop ? ($loop->status=='Published' ? 'selected="true"' : '') : '' ?> value="Published">Published</option>
                    <?php } ?>
                    <option <?= $loop ? ($loop->status=='Expired' ? 'selected="true"' : '') : '' ?> value="Published">Expired</option>
                </select>
            </td>
        </tr>
        <tr>
            <td>Start date:</td>
            <td>
                <input type="text" name="startdate" size="10" maxlength="10" value="<?= $loop ? $loop->startdate : date('Y-m-d') ?>" />
                <span class="btn btn-sm btn-default" id="startdate_today">today</span>
            </td>
            <td>
           </td>
        </tr>
        <tr>
            <td>Expiration date:</td>
            <td>
                <input type="text" name="expires" size="10" maxlength="10" value="<?= $loop ? $loop->expires : '' ?>" />
                <span class="btn btn-sm btn-default" id="expires_never">never</span>
                <br/>
                If this event expires, should it be re-enabled on the starting date the following year?<br/>
                <select class="form-control" name="annual">
                <option value="0" <?= ($loop and $loop->annual) ? '' : 'selected="true"' ?> >No, do not automatically re-enable</option>
                <option value="1" <?= ($loop and $loop->annual) ? 'selected="true"' : '' ?> >Yes, re-enable this loop each year</option>
                </select>
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>Source</td>
            <td><input class="form-control" type="text" name="source" maxlength="100" value="<?= $loop ? htmlspecialchars($loop->source) : '' ?>" /></td>
        </tr>
        <tr>
            <td>Edited by</td>
            <td><input class="form-control" type="text" name="editedby" maxlength="100" value="<?= $loop ? htmlspecialchars($loop->editedby) : '' ?>" /></td>
        </tr>
        <tr>
            <td>Hiking?</td>
            <td><input class="form-control" type="text" name="hike" value="<?= $loop ? $loop->hike : '' ?>" readonly="readonly" /></td>
        </tr>
        <tr>
            <td>Bikes?</td>
            <td><input class="form-control" type="text" name="bike" value="<?= $loop ? $loop->bike : '' ?>" readonly="readonly" /></td>
        </tr>
        <tr>
            <td>Equestrian?</td>
            <td><input class="form-control" type="text" name="bridle" value="<?= $loop ? $loop->bridle : '' ?>" readonly="readonly" /></td>
        </tr>
        <tr>
            <td>Mountain Biking?</td>
            <td><input class="form-control" type="text" name="mountainbike" value="<?= $loop ? $loop->mountainbike : '' ?>" readonly="readonly" /></td>
        </tr>
        <tr>
            <td>Paved?</td>
            <td><input class="form-control" type="text" name="paved" value="<?= $loop ? $loop->paved : '' ?>" readonly="readonly" /></td>
        </tr>
        <tr>
            <td>Difficulty (bikes)</td>
            <td><input class="form-control" type="text" name="dificulty" value="<?= $loop ? $loop->difficulty : '' ?>" readonly="readonly" /></td>
        </tr>
        <tr>
            <td colspan="2">
                <img src="<?= $loop ? ssl_url("static/photos/loops/{$loop->id}.jpg") : ssl_url('static/common/blank.png') ?>" id="elevation_profile" />
            </td>
        </tr>
        </table>
    </td>
    <td>
        <table id="directions">
        </table>

        <table>
        <tr>
            <td>Length</td>
            <td><input type="text" readonly="readonly" class="shortversion" name="distance_feet" value="<?= $loop ? $loop->distance_feet : 0 ?>" /> feet</td>
            <td><input type="text" readonly="readonly" class="longversion" name="distancetext" value="<?= $loop ? $loop->distancetext : 0 ?>" /></td>
        </tr>
        <tr>
            <td>Duration, hike</td>
            <td><input type="text" readonly="readonly" class="shortversion" name="duration_hike" value="<?= $loop ? $loop->duration_hike : 0 ?>" /> seconds</td>
            <td><input type="text" readonly="readonly" class="longversion" name="durationtext_hike" value="<?= $loop ? $loop->durationtext_hike : 0 ?>" /></td>
        </tr>
        <tr>
            <td>Duration, bicycle</td>
            <td><input type="text" readonly="readonly" class="shortversion" name="duration_bike" value="<?= $loop ? $loop->duration_bike : 0 ?>" /> seconds</td>
            <td><input type="text" readonly="readonly" class="longversion" name="durationtext_bike" value="<?= $loop ? $loop->durationtext_bike : 0 ?>" /></td>
        </tr>
        <tr>
            <td>Duration, equestrian</td>
            <td><input type="text" readonly="readonly" class="shortversion" name="duration_bridle" value="<?= $loop ? $loop->duration_bridle : 0 ?>" /> seconds</td>
            <td><input type="text" readonly="readonly" class="longversion" name="durationtext_bridle" value="<?= $loop ? $loop->durationtext_bridle : 0 ?>" /></td>
        </tr>
        </table>
    </td>
</tr>
<tr>
    <th colspan="2">Waypoints and Route</th>
</tr>
<tr>
    <td>
        <div id="map_canvas"></div>

        <div>
            Search for an address or landmark: <input type="text" id="geocode_text" /> <input type="button" id="geocode_button" value="Go &gt;" />
        </div>
    </td>
    <td>
        <ol style="font-size:80%;">
            <li>Start by zooming the map to the general area of your desired loop.</li>
            <li>Lay down the first and last waypoints, then click Recalculate to get an idea of where the computer would route you. The routing system will automatically &quot;close the loop&quot; back to the first waypoint.</li>
            <li>To fine-tune the route, add waypoints in between and Recalculate.</li>
        </ol>
        <table id="waypoints">
            <tr class="waypoint" id="wp0">
                <td>Waypoint 0:</td>
                <td><input type="text" readonly="readonly" class="form-control lat" name="wp0lat" value="<?= $loop ? $loop->wp0lat : 0 ?>" /></td>
                <td><input type="text" readonly="readonly" class="form-control lng" name="wp0lng" value="<?= $loop ? $loop->wp0lng : 0 ?>" /></td>
                <td><span class="btn btn-sm btn-default wpadd" wp="wp0">add</span><span class="btn btn-sm btn-default wpremove" wp="wp0">remove</span></td>
            </tr>
            <tr class="waypoint" id="wp1">
                <td>Waypoint 1:</td>
                <td><input type="text" readonly="readonly" class="form-control lat" name="wp1lat" value="<?= $loop ? $loop->wp1lat : 0 ?>" /></td>
                <td><input type="text" readonly="readonly" class="form-control lng" name="wp1lng" value="<?= $loop ? $loop->wp1lng : 0 ?>" /></td>
                <td><span class="btn btn-sm btn-default wpadd" wp="wp1">add</span><span class="btn btn-sm btn-default wpremove" wp="wp1">remove</span></td>
            </tr>
            <tr class="waypoint" id="wp2">
                <td>Waypoint 2:</td>
                <td><input type="text" readonly="readonly" class="form-control lat" name="wp2lat" value="<?= $loop ? $loop->wp2lat : 0 ?>" /></td>
                <td><input type="text" readonly="readonly" class="form-control lng" name="wp2lng" value="<?= $loop ? $loop->wp2lng : 0 ?>" /></td>
                <td><span class="btn btn-sm btn-default wpadd" wp="wp2">add</span><span class="btn btn-sm btn-default wpremove" wp="wp2">remove</span></td>
            </tr>
            <tr class="waypoint" id="wp3">
                <td>Waypoint 3:</td>
                <td><input type="text" readonly="readonly" class="form-control lat" name="wp3lat" value="<?= $loop ? $loop->wp3lat : 0 ?>" /></td>
                <td><input type="text" readonly="readonly" class="form-control lng" name="wp3lng" value="<?= $loop ? $loop->wp3lng : 0 ?>" /></td>
                <td><span class="btn btn-sm btn-default wpadd" wp="wp3">add</span><span class="btn btn-sm btn-default wpremove" wp="wp3">remove</span></td>
            </tr>
            <tr class="waypoint" id="wp4">
                <td>Waypoint 4:</td>
                <td><input type="text" readonly="readonly" class="form-control lat" name="wp4lat" value="<?= $loop ? $loop->wp4lat : 0 ?>" /></td>
                <td><input type="text" readonly="readonly" class="form-control lng" name="wp4lng" value="<?= $loop ? $loop->wp4lng : 0 ?>" /></td>
                <td><span class="btn btn-sm btn-default wpadd" wp="wp4">add</span><span class="btn btn-sm btn-default wpremove" wp="wp4">remove</span></td>
            </tr>
            <tr class="waypoint" id="wp5">
                <td>Waypoint 5:</td>
                <td><input type="text" readonly="readonly" class="form-control lat" name="wp5lat" value="<?= $loop ? $loop->wp5lat : 0 ?>" /></td>
                <td><input type="text" readonly="readonly" class="form-control lng" name="wp5lng" value="<?= $loop ? $loop->wp5lng : 0 ?>" /></td>
                <td><span class="btn btn-sm btn-default wpadd" wp="wp5">add</span><span class="btn btn-sm btn-default wpremove" wp="wp5">remove</span></td>
            </tr>
            <tr class="waypoint" id="wp6">
                <td>Waypoint 6:</td>
                <td><input type="text" readonly="readonly" class="form-control lat" name="wp6lat" value="<?= $loop ? $loop->wp6lat : 0 ?>" /></td>
                <td><input type="text" readonly="readonly" class="form-control lng" name="wp6lng" value="<?= $loop ? $loop->wp6lng : 0 ?>" /></td>
                <td><span class="btn btn-sm btn-default wpadd" wp="wp6">add</span><span class="btn btn-sm btn-default wpremove" wp="wp6">remove</span></td>
            </tr>
            <tr class="waypoint" id="wp7">
                <td>Waypoint 7:</td>
                <td><input type="text" readonly="readonly" class="form-control lat" name="wp7lat" value="<?= $loop ? $loop->wp7lat : 0 ?>" /></td>
                <td><input type="text" readonly="readonly" class="form-control lng" name="wp7lng" value="<?= $loop ? $loop->wp7lng : 0 ?>" /></td>
                <td><span class="btn btn-sm btn-default wpadd" wp="wp7">add</span><span class="btn btn-sm btn-default wpremove" wp="wp7">remove</span></td>
            </tr>
            <tr class="waypoint" id="wp8">
                <td>Waypoint 8:</td>
                <td><input type="text" readonly="readonly" class="form-control lat" name="wp8lat" value="<?= $loop ? $loop->wp8lat : 0 ?>" /></td>
                <td><input type="text" readonly="readonly" class="form-control lng" name="wp8lng" value="<?= $loop ? $loop->wp8lng : 0 ?>" /></td>
                <td><span class="btn btn-sm btn-default wpadd" wp="wp8">add</span><span class="btn btn-sm btn-default wpremove" wp="wp8">remove</span></td>
            </tr>
            <tr class="waypoint" id="wp9">
                <td>Waypoint 9:</td>
                <td><input type="text" readonly="readonly" class="form-control lat" name="wp9lat" value="<?= $loop ? $loop->wp9lat : 0 ?>" /></td>
                <td><input type="text" readonly="readonly" class="form-control lng" name="wp9lng" value="<?= $loop ? $loop->wp9lng : 0 ?>" /></td>
                <td><span class="btn btn-sm btn-default wpadd" wp="wp9">add</span><span class="btn btn-sm btn-default wpremove" wp="wp9">remove</span></td>
            </tr>
            <tr>
                <td>Loop?</td>
                <td colspan="3">
                    <select class="form-control" name="closedloop">
                        <option value="1" <?= $loop ? ($loop->closedloop=='1' ? 'selected="true"' : '') : '' ?> >Return to start to form a closed loop</option>
                        <option value="0" <?= $loop ? ($loop->closedloop=='0' ? 'selected="true"' : '') : '' ?> >End at the final waypoint, not a closed loop</option>
                    </select>
                </td>
            </tr>
            <tr>
                <td>Filter</td>
                <td colspan="3">
                <select class="form-control" name="terrain_filter">
                    <option value="hike" <?= $loop ? ($loop->terrain_filter=='hike' ? 'selected="true"' : '') : '' ?> >Hiking trails</option>
                    <option value="hike_paved" <?= $loop ? ($loop->terrain_filter=='hike_paved' ? 'selected="true"' : '') : '' ?> >Hiking trails, paved</option>
                    <option value="hike_unpaved" <?= $loop ? ($loop->terrain_filter=='hike_unpaved' ? 'selected="true"' : '') : '' ?> >Hiking trails, unpaved</option>
                    <option value="bike" <?= $loop ? ($loop->terrain_filter=='bike' ? 'selected="true"' : '') : '' ?> >Bicycle trails</option>
                    <option value="bike_novice" <?= $loop ? ($loop->terrain_filter=='bike_novice' ? 'selected="true"' : '') : '' ?> >Bicycle trails, novice</option>
                    <option value="bike_beginner" <?= $loop ? ($loop->terrain_filter=='bike_beginner' ? 'selected="true"' : '') : '' ?> >Bicycle trails &amp; roads, beginner</option>
                    <option value="bike_intermediate" <?= $loop ? ($loop->terrain_filter=='bike_intermediate' ? 'selected="true"' : '') : '' ?> >Bicycle trails &amp; roads, intermediate</option>
                    <option value="bike_advanced" <?= $loop ? ($loop->terrain_filter=='bike_advanced' ? 'selected="true"' : '') : '' ?> >Bicycle trails &amp; roads, advanced</option>
                    <option value="bridle" <?= $loop ? ($loop->terrain_filter=='bridle' ? 'selected="true"' : '') : '' ?> >Equestrian trails</option>
                    <option value="bridle_paved" <?= $loop ? ($loop->terrain_filter=='bridle_paved' ? 'selected="true"' : '') : '' ?> >Equestrian trails, paved</option>
                    <option value="bridle_unpaved" <?= $loop ? ($loop->terrain_filter=='bridle_unpaved' ? 'selected="true"' : '') : '' ?> >Equestrian trails, unpaved</option>
                </select>
                </td>
            </tr>
            <tr>
                <td>Trim?</td>
                <td colspan="3">
                <select class="form-control" name="trim_spurs">
                    <option value="">Do not trim off spurs</option>
                    <option value="trim">Trim off spurs</option>
                </select>
                </td>
            </tr>
            <tr>
                <td></td>
                <td><input type="button" id="recalculate_button" value="Recalculate" value0="One moment..." value1="Recalculate" class="btn btn-default" /></td>
                <td></td>
                <td></td>
            </tr>
        </table>

        <br/>

        <ol style="font-size:80%;">
            <li>Center the map and place Waypoint 0 to indicate a starting point.</li>
            <li>Select trail settings above: the trail types filter and whether to close the loop.</li>
            <li>Select a route length below.</li>
            <li>Click the Generate Random button to have it select some waypoints and place markers.</li>
            <li>Click Generate Random again to try again, click the Recalculate button to calculate a route, or adjust the markers to fine tune the output.</li>
        </ol>

        Desired route length: <select class="form-control" id="random_miles">
            <option value="5">5 miles</option>
            <option value="10">10 miles</option>
            <option value="15">15 miles</option>
            <option value="20">20 miles</option>
            <option value="25">25 miles</option>
            <option value="30">30 miles</option>
        </select>
        <input type="button" id="random_button" value="Generate Random" value0="One moment..." value1="Generate Random" class="btn btn-default" />

    </td>
</tr>
<tr>
    <th>&nbsp;</th>
</tr>
</table>

<p><input type="submit" value="Save Changes" class="btn btn-primary" /></p>

</form>


<?php if ($loop) { ?>
<form id="deleteform" method="post" action="<?= ssl_url("contributors/deleteloop/") ?>" onSubmit="return confirm('Really delete this loop?');">
<input type="hidden" name="id" value="<?= $loop->id ?>" />
<input type="submit" value="Delete" class="btn btn-primary" />
</form>
<?php } ?>