<?php $this->page_title = isset($loop->id) ? 'Edit Loop' : 'Create Loop'; ?>

<script type="text/javascript">
    loop_steps = <?= $loop ? $loop->steps : '[]' ?>;
</script>

<form class="form-horizontal" id="loopform" method="post" action="<?= ssl_url("contributors/saveloop/") ?>">

<input type="hidden" name="id" value="<?= $loop ? $loop->id : 0 ?>" />
<input type="hidden" name="wkt" value="<?= $loop ? $loop->wkt : '' ?>" />
<input type="hidden" name="elevation_profile" value="<?= $loop ? $loop->elevation_profile : '' ?>" />
<input type="hidden" name="elevation_profile_image" value="<?= $loop ? ssl_url("static/common/images/loops/{$loop->id}.jpg") : '' ?>" />

<ul class="nav nav-tabs">
  <li class="active"><a data-toggle="tab" href="#basic-info">Basic Information</a></li>
  <li><a data-toggle="tab" href="#waypoints-route">Waypoints &amp; Route</a></li>
  <li><a data-toggle="tab" href="#directions-profile">Directions &amp; Profile</a></li>
</ul>

<div class="tab-content">

<!-- Basic Information (tab) -->
<div id="basic-info" class="tab-pane active">
    <h3>Basic Information</h3>

    <!-- Basic Information (col) -->
    <div class="col-md-6">

        <div class="form-group">
            <label class="control-label col-sm-3">Name:</label>
            <div class="col-sm-8">
                <input class="form-control" type="text" name="name" maxlength="200" value="<?= $loop ? htmlspecialchars($loop->name) : '- Untitled Loop' ?>" />
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-3">Description:</label>
            <div class="col-sm-8">
                <textarea class="form-control" name="description" style="height:5em">
                    <?= $loop ? htmlspecialchars($loop->description) : '' ?>
                </textarea>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-3">Publication</label>
            <div class="col-sm-8">
                <select class="form-control" name="status">
                    <option <?= $loop ? ($loop->status=='New' ? 'selected="true"' : '') : '' ?> value="New">New</option>
                    <option <?= $loop ? ($loop->status=='In Progress' ? 'selected="true"' : '') : '' ?> value="In Progress">In Progress</option>
                    <?php if ($this->loggedin['admin']) { ?>
                    <option <?= $loop ? ($loop->status=='Published' ? 'selected="true"' : '') : '' ?> value="Published">Published</option>
                    <?php } ?>
                    <option <?= $loop ? ($loop->status=='Expired' ? 'selected="true"' : '') : '' ?> value="Published">Expired</option>
                </select>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-3">Start date:</label>
            <div class="col-sm-8">
                <input type="text" name="startdate" size="10" maxlength="10" value="<?= $loop ? $loop->startdate : date('Y-m-d') ?>" />
                <span class="btn btn-sm btn-default" id="startdate_today">today</span>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-3">Expiration date:</label>
            <div class="col-sm-8">
                <input type="text" name="expires" size="10" maxlength="10" value="<?= $loop ? $loop->expires : '' ?>" />
                <span class="btn btn-sm btn-default" id="expires_never">never</span>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-3">Repeat:</label>
            <div class="col-sm-8">
                <select class="form-control" name="annual">
                    <option value="0" <?= ($loop and $loop->annual) ? '' : 'selected="true"' ?> >No, do not automatically re-enable</option>
                    <option value="1" <?= ($loop and $loop->annual) ? 'selected="true"' : '' ?> >Yes, re-enable this loop each year</option>
                </select>
                <p class="help-block">If this event expires, should it be re-enabled on the starting date the following year?<br/>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-3">Source:</label>
            <div class="col-sm-8">
                <input class="form-control" type="text" name="source" maxlength="100" value="<?= $loop ? htmlspecialchars($loop->source) : '' ?>" />
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-3">Edited by:</label>
            <div class="col-sm-8">
                <input class="form-control" type="text" name="editedby" maxlength="100" value="<?= $loop ? htmlspecialchars($loop->editedby) : '' ?>" />
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-3">Hiking:</label>
            <div class="col-sm-8">
                <input class="form-control" type="text" name="hike" value="<?= $loop ? $loop->hike : '' ?>" readonly="readonly" />
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-3">Bikes:</label>
            <div class="col-sm-8">
                <input class="form-control" type="text" name="bike" value="<?= $loop ? $loop->bike : '' ?>" readonly="readonly" />
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-3">Equestrian:</label>
            <div class="col-sm-8">
                <input class="form-control" type="text" name="bridle" value="<?= $loop ? $loop->bridle : '' ?>" readonly="readonly" />
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-3">Mountain Biking:</label>
            <div class="col-sm-8">
                <input class="form-control" type="text" name="mountainbike" value="<?= $loop ? $loop->mountainbike : '' ?>" readonly="readonly" />
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-3">Paved:</label>
            <div class="col-sm-8">
                <input class="form-control" type="text" name="paved" value="<?= $loop ? $loop->paved : '' ?>" readonly="readonly" />
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-3">Difficulty (bikes):</label>
            <div class="col-sm-8">
                <input class="form-control" type="text" name="dificulty" value="<?= $loop ? $loop->difficulty : '' ?>" readonly="readonly" />
            </div>
        </div>

    </div>
    <!-- /Basic Information (col) -->

</div>
<!-- /Basic Information (tab) -->


<div id="waypoints-route" class="tab-pane">
    <h3>Waypoints &amp; Route</h3>

    <!-- Waypoints Map - Left side (col) -->
    <div class="col-md-6">

        <div id="map_canvas" style="width:100%; height:5in; margin: 1em 0;"></div>

        <div class="form-group">
            <label class="control-label col-sm-4">Search:</label>
            <div class="col-sm-8 form-inline">
                <input class="form-control" type="text" id="geocode_text" />
                <input class="btn btn-sm btn-default" type="button" id="geocode_button" value="Go &gt;" />
                <p class="help-block">Search for an address or landmark</p>
            </div>
        </div>

    </div>
    <!-- /Waypoints Map - Left side (col) -->

    <!-- Waypoints Right side (col) -->
    <div class="col-md-6">

        <!-- Waypoints List (row) -->
        <div class="row">

            <h4>Waypoints <a href="#waypointInstructions" data-toggle="collapse" aria-expanded="false" aria-controls="waypointInstructions"><span class="glyphicon glyphicon-question-sign"></span></a></h4>

            <div class="collapse well well-sm" id="waypointInstructions">
                <ol>
                    <li>Zoom the map to the general area of your desired loop.</li>
                    <li>Add the first and last waypoints, then click <em>Recalculate</em> to get an idea of where the system would route you. The system will automatically &quot;close the loop&quot; back     to      the first waypoint.</li>
                    <li>To fine-tune the route: add waypoints in between and <em>Recalculate</em>.</li>
                </ol>
            </div>

            <ul id="waypoints" class="list-group">
            <?php for ($i=0; $i<10; $i++) : ?>
                <li class="list-group-item waypoint" id="wp<?= $i ?>">
                    <label class="control-label"><?= $i ?>:</label>
                    <input type="text" class="lat textonly" readonly="readonly" id="wp<?= $i ?>lat" name="wp<?= $i ?>lat" value="<?= $loop ? $loop->{"wp${i}lat"} : '0' ?>" />
                    <input type="text" class="lng textonly" readonly="readonly" id="wp<?= $i ?>lng" name="wp<?= $i ?>lng" value="<?= $loop ? $loop->{"wp${i}lng"} : '0' ?>" />
                    <span class="btn btn-sm btn-default wpadd pull-right" wp="wp<?= $i ?>">add</span>
                    <span class="btn btn-sm btn-default wpremove pull-right" wp="wp<?= $i ?>">remove</span>
                </li>
            <?php endfor; ?>
            </ul>

        </div>
        <!-- /Waypoints List (row) -->

        <!-- Route Options (row) -->
        <div class="row">

            <h4>Route Options</h4>

            <div class="form-group">
                <label class="control-label col-sm-3">Loop:</label>
                <div class="col-sm-6">
                    <select class="form-control" name="closedloop">
                        <option value="1" <?= $loop ? ($loop->closedloop=='1' ? 'selected="true"' : '') : '' ?> >Return to start to form a closed loop</option>
                        <option value="0" <?= $loop ? ($loop->closedloop=='0' ? 'selected="true"' : '') : '' ?> >End at the final waypoint, not a closed loop</option>
                    </select>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-sm-3">Filter:</label>
                <div class="col-sm-6">
                    <select class="form-control" name="terrain_filter">
                        <option value="hike" <?= $loop ? ($loop->terrain_filter=='hike' ? 'selected="true"' : '') : '' ?> >Hiking trails</option>
                        <option value="hike_paved" <?= $loop ? ($loop->terrain_filter=='hike_paved' ? 'selected="true"' : '') : '' ?> >Hiking trails, paved</option>
                        <option value="hike_unpaved" <?= $loop ? ($loop->terrain_filter=='hike_unpaved' ? 'selected="true"' : '') : '' ?> >Hiking trails, unpaved</option>
                        <option value="bike" <?= $loop ? ($loop->terrain_filter=='bike' ? 'selected="true"' : '') : '' ?> >Bicycle trails</option>
                        <option value="bike_novice" <?= $loop ? ($loop->terrain_filter=='bike_novice' ? 'selected="true"' : '') : '' ?> >Bicycle trails, novice</option>
                        <option value="bike_beginner" <?= $loop ? ($loop->terrain_filter=='bike_beginner' ? 'selected="true"' : '') : '' ?> >Bicycle trails &amp; roads, beginner</option>
                        <option value="bike_intermediate" <?= $loop ? ($loop->terrain_filter=='bike_intermediate' ? 'selected="true"' : '') : '' ?> >Bicycle trails &amp; roads, intermediate</option>
                        <option value="bike_advanced" <?= $loop ? ($loop->terrain_filter=='bike_advanced' ? 'selected="true"' : '') : '' ?> >Bicycle trails &amp; roads, advanced</option>
                        <option value="bridle" <?= $loop ? ($loop->terrain_filter=='bridle' ? 'selected="true"' : '') : '' ?> >Equestrian trails</option>
                        <option value="bridle_paved" <?= $loop ? ($loop->terrain_filter=='bridle_paved' ? 'selected="true"' : '') : '' ?> >Equestrian trails, paved</option>
                        <option value="bridle_unpaved" <?= $loop ? ($loop->terrain_filter=='bridle_unpaved' ? 'selected="true"' : '') : '' ?> >Equestrian trails, unpaved</option>
                    </select>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-sm-3">Trim:</label>
                <div class="col-sm-6">
                    <select class="form-control" name="trim_spurs">
                        <option value="">Do not trim off spurs</option>
                        <option value="trim">Trim off spurs</option>
                    </select>
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-offset-3 col-sm-6">
                    <input type="button" id="recalculate_button" value="Recalculate" value0="One moment..." value1="Recalculate" class="btn btn-default" />
                </div>
            </div>

        </div>
        <!-- /Route Options (row) -->

        <!-- Random Loops (row) -->
        <div class="row">

            <h4>Generate Random Loop <a href="#randomLoopInstructions" data-toggle="collapse" aria-expanded="false" aria-controls="randomLoopInstructions"><span class="glyphicon glyphicon-question-sign"></span></a></h4>

            <div class="collapse well well-sm" id="randomLoopInstructions">
                <ol>
                    <li>Center the map and place Waypoint 0 to indicate a starting point.</li>
                    <li>Select trail settings above: the trail types filter and whether to close the loop.</li>
                    <li>Select a desired route length below.</li>
                    <li>Click the Generate Random button to have it select some waypoints and place markers.</li>
                    <li>Click Generate Random again to try again, click the Recalculate button to calculate a route, or adjust the markers to fine tune the output.</li>
                </ol>
            </div>

            <div class="form-group">
                <label class="control-label col-sm-3">Route length:</label>
                <div class="col-sm-6">
                    <select class="form-control" id="random_miles">
                        <option value="5">5 miles</option>
                        <option value="10">10 miles</option>
                        <option value="15">15 miles</option>
                        <option value="20">20 miles</option>
                        <option value="25">25 miles</option>
                        <option value="30">30 miles</option>
                    </select>
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-offset-3 col-sm-6">
                    <input type="button" id="random_button" value="Generate Random" value0="One moment..." value1="Generate Random" class="btn btn-default" />
                </div>
            </div>

        </div>
        <!-- /Random Loops (row) -->

    </div>
    <!-- Waypoints Right side (col) -->

</div>
<!-- /Waypoints & Route (tab) -->



<!-- /Directions & Profile (tab) -->
<div id="directions-profile" class="tab-pane">

    <h3>Directions &amp; Profile</h3>

    <!-- Directions (col) -->
    <div class="col-md-6">

    <h4>Directions</h4>

        <div class="row">
             <table class="table table-striped table-condensed" id="directions" style="font-size:90%;">
             </table>
        </div>

    </div>
    <!-- /Directions (col) -->

    <!-- Distance (col) -->
    <div class="col-md-6">

        <h4>Distance</h4>

        <div class="row">
            <label class="col-sm-4">Length:</label>
            <div class="col-sm-8">
                <input type="hidden" name="distancetext" value="<?= $loop ? $loop->distancetext : 0 ?>" />
                <input type="hidden" name="distance_feet" value="<?= $loop ? $loop->distance_feet : 0 ?>" />
                <span id="distancetext"><?= $loop ? $loop->distancetext : 0 ?></span> (<span id="distance_feet"><?= $loop ? $loop->distance_feet : 0 ?></span> ft)
            </div>
        </div>

        <div class="row">
            <label class="col-sm-4">Duration, hike:</label>
            <div class="col-sm-8">
                <input type="hidden" name="durationtext_hike" value="<?= $loop ? $loop->durationtext_hike : 0 ?>" />
                <input type="hidden" name="duration_hike" value="<?= $loop ? $loop->duration_hike : 0 ?>" />
                <span id="durationtext_hike"><?= $loop ? $loop->durationtext_hike : 0 ?></span> (<span id="duration_hike"><?= $loop ? $loop->duration_hike : 0 ?></span> sec)
            </div>
        </div>

        <div class="row">
            <label class="col-sm-4">Duration, bicycle:</label>
            <div class="col-sm-8">
                <input type="hidden" name="durationtext_bike" value="<?= $loop ? $loop->durationtext_bike : 0 ?>" />
                <input type="hidden" name="duration_bike" value="<?= $loop ? $loop->duration_bike : 0 ?>" />
                <span id="durationtext_bike"><?= $loop ? $loop->durationtext_bike : 0 ?></span> (<span id="duration_bike"><?= $loop ? $loop->duration_bike : 0 ?></span> sec)
            </div>
        </div>

        <div class="row">
            <label class="col-sm-4">Duration, equestrian:</label>
            <div class="col-sm-8">
                <input type="hidden" name="durationtext_bridle" value="<?= $loop ? $loop->durationtext_bridle : 0 ?>" />
                <input type="hidden" name="duration_bridle" value="<?= $loop ? $loop->duration_bridle : 0 ?>" />
                <span id="durationtext_bridle"><?= $loop ? $loop->durationtext_bridle : 0 ?></span> (<span id="duration_bridle"><?= $loop ? $loop->duration_bridle : 0 ?></span> sec)
            </div>
        </div>

    </div>
    <!-- /Distance (col) -->

    <!-- Elevation Profile (col) -->
    <div class="col-md-6">

        <h4>Elevation Profile</h4>

        <div class="form-group">
            <div class="col-sm-6">
                <img src="<?= $loop ? ssl_url("static/common/images/loops/{$loop->id}.jpg") : ssl_url('static/common/images/blank.png') ?>" id="elevation_profile" />
            </div>
        </div>

    </div>
    <!-- /Elevation Profile -->

</div>
<!-- /Directions & Profile (tab) -->


</div>
<!-- /Tabs content -->

<!-- Submit Button -->
<div class="form-group">
    <div class="col-md-12">
        <input class="btn btn-primary" type="submit" value="Save Changes" />
    </div>
</div>
<!-- /Submit Button -->

</form>


<!-- Delete Button -->
<?php if ($loop) { ?>
<form class="form-horizontal" id="deleteform" method="post" action="<?= ssl_url("contributors/deleteloop/") ?>" onSubmit="return confirm('Really delete this loop?');">
    <input type="hidden" name="id" value="<?= $loop->id ?>" />
    <div class="form-group">
        <div class="col-sm-4">
            <input class="btn btn-primary" type="submit" value="Delete Loop" />
        </div>
    </div>
</form>
<?php } ?>
<!-- /Delete Button -->