<?php $this->page_title = 'Loops'; ?>

<ul class="local-actions">
    <li><a href="<?= ssl_url('contributors/loop/0') ?>" class="btn btn-primary">+ Create a loop</a></li>
</ul>

<table id="loops" class="table table-striped">
<thead>
<tr>
    <th>Name</th>
    <th>Editor</th>
    <th>Status</th>
    <th>Miles</th>
    <th>Closed</th>
    <th>Hike</th>
    <th>Bike</th>
    <th>Bridle</th>
    <th>MtnBike</th>
    <th>Edit</th>
    <th>Clone</th>
    <th>Delete</th>
</tr>
</thead>
<tbody>
<?php foreach ($loops as $loop) { ?>
<tr>
    <td>
        <?php if ($this->loggedin['admin'] or ($loop->creatorid == $this->loggedin['id'])): ?>
            <a href="<?= ssl_url("contributors/loop/{$loop->id}/edit") ?>"><?= htmlspecialchars($loop->name) ?></a>
        <?php else: ?>
            <?= htmlspecialchars($loop->name) ?>
        <?php endif; ?>
    </td>
    <td style="text-align:left;"><?= htmlspecialchars($loop->editedby) ?></td>
    <td style="text-align:right;"><?= $loop->status ?></td>
    <td style="text-align:right;"><?= (float) $loop->distancetext ?></td>
    <td style="text-align:right;"><?= $loop->closedloop == '1' ? 'Loop' : 'One-Way' ?></td>
    <td style="text-align:right;"><?= $loop->hike ?></td>
    <td style="text-align:right;"><?= $loop->bike ?></td>
    <td style="text-align:right;"><?= $loop->bridle ?></td>
    <td style="text-align:right;"><?= $loop->mountainbike ?></td>
    <td>
        <?php if ($this->loggedin['admin'] or ($loop->creatorid == $this->loggedin['id'])): ?>
            <a href="<?= ssl_url("contributors/loop/{$loop->id}/edit") ?>">edit</a>
        <?php else: ?>
            &nbsp;
        <?php endif; ?>
    </td>
    <td><a class="clone" href="<?= ssl_url("contributors/loop/{$loop->id}/clone") ?>">clone</a></td>
    <td><a href="<?= ssl_url("contributors/loop/{$loop->id}/delete") ?>">delete</a></td>
</tr>
<?php } ?>
</tbody>
</table>




<script type="text/javascript">
$(document).ready(function() {
    // sort the table
    $('#loops').tablesorter({
        sortList: [[2,0],[0,0]]
    });
    $('#loops').addClass('tablesorter');

    // the clone links are simple links, but do ask for confirmation first
    $('a.clone').click(function () {
        if (! confirm("This will make a copy of the Loop, for your own editing and experimentation.\nClick OK to continue, or Cancel to cancel.") ) return false;
        return true;
    });
});
</script>