<?php $this->page_title = 'Delete Loop'; ?>

<form class="form-horizontal" id="loopform" method="post" action="<?= ssl_url("contributors/loop/" . $loop->id . "/delete") ?>">

<p>Are you sure you want to permanently delete the loop, <em>"<?= $loop->name ?>"</em>?</p>

<div class="form-group">
    <div class="col-sm-4">
        <input class="btn btn-primary" type="submit" name="submit" value="Delete" />
        <a class="btn btn-primary" href="/contributors/loops" role="button">Cancel</a>
    </div>
</div>

</form>