<?php $this->load->view('contributors/header.phtml') ?>

<p>Select a menu above.</p>

<ul>
    <li><b>Main Menu</b> -- This help text.</li>
    <li><b>Markers</b> -- A list of Markers (Health Tips) which you have posted.</li>
    <li><b>Expired Markers</b> -- The same list as Markers, but filtered to show only those with an expiration date in the past.</li>
    <li><b>Closures</b> -- Manage trail closures.</li>
    <li><b>Loops</b> -- Manage <i>featured Loops &amp; Trails</i>.</li>
    <li><b>Tweet</b> -- Opens an interface to Twitter to post a message to the #ClevelandParks hashtag. These messages wll appear on the front-facing map.</li>
    <li><b>Log Out</b> -- End your session and require you to login again.</li>
</ul>

<p>You may not see all of these menus, depending on your account's configuration. For more information, contact the administrator.</p>

<?php $this->load->view('contributors/footer.phtml') ?>
