<?php $this->page_title = 'Markers'; ?>

<ul class="local-actions">
    <li><a href="<?= ssl_url('contributors/marker/0') ?>" class="btn btn-primary">+ Create a marker</a></li>
</ul>

<h2>My Markers</h2>
<?php if ($markers_count): ?>
<table id="markers" class="table table-striped">
<thead>
<tr>
    <th>Title</th>
    <th>Enabled</th>
    <th>Starts</th>
    <th>Expires</th>
    <th>Category</th>
    <th>Content</th>
    <th>Edit</th>
    <th>Delete</th>
</tr>
</thead>
<tbody>
<?php foreach ($markers as $marker): ?>
<tr>
    <td><a href="<?= ssl_url("contributors/marker/{$marker->id}/edit") ?>"><?= htmlspecialchars($marker->title) ?></a></td>
    <td><?= $marker->enabled ? 'Yes' : 'No' ?></td>
    <td><?= $marker->startdate ?></td>
    <td><?= $marker->expires ?></td>
    <td><?= htmlspecialchars($marker->category) ?></td>
    <td><?= htmlspecialchars(strip_tags(substr($marker->content,0,200))) ?></td>
    <td><a href="<?= ssl_url("contributors/marker/{$marker->id}/edit") ?>">edit</a></td>
    <td><a href="<?= ssl_url("contributors/marker/{$marker->id}/delete") ?>">delete</a></td>
</tr>
<?php endforeach; ?>
</tbody>
</table>
<?php else: ?>
<p>You have no markers.</p>
<?php endif; ?>



<?php if ($this->loggedin['admin']): ?>
<h2>Other Markers</h2>
<?php if ($other_markers_count): ?>
<table id="other_markers" class="table table-striped">
<thead>
<tr>
    <th>Title</th>
    <th>Enabled</th>
    <th>Starts</th>
    <th>Expires</th>
    <th>Category</th>
    <th>Content</th>
    <th>Edit</th>
    <th>Delete</th>
</tr>
</thead>
<tbody>
<?php foreach ($other_markers as $marker): ?>
<tr>
    <td><a href="<?= ssl_url("contributors/marker/{$marker->id}/edit") ?>"><?= htmlspecialchars($marker->title) ?></a></td>
    <td><?= $marker->enabled ? 'Yes' : 'No' ?></td>
    <td><?= $marker->startdate ?></td>
    <td><?= $marker->expires ?></td>
    <td><?= htmlspecialchars($marker->category) ?></td>
    <td><?= htmlspecialchars(strip_tags(substr($marker->content,0,200))) ?></td>
    <td><a href="<?= ssl_url("contributors/marker/{$marker->id}/edit") ?>">edit</a></td>
    <td><a href="<?= ssl_url("contributors/marker/{$marker->id}/delete") ?>">delete</a></td>
</tr>
<?php endforeach; ?>
</tbody>
</table>
<?php else: ?>
<p>There are no other markers.</p>
<?php endif; ?>
<?php endif; ?>


<script type="text/javascript">
$(document).ready(function() {
    $('#markers').tablesorter({
        sortList: [[2,0],[3,0]]
    });
    $('#markers').addClass('tablesorter');
});

$(document).ready(function() {
    $('#other_markers').tablesorter({
        sortList: [[2,0],[3,0]]
    });
    $('#other_markers').addClass('tablesorter');
});
</script>