<?php $this->page_title = 'Markers'; ?>

<style type="text/css">
table.tablesorter thead tr .header {
    background-position: left center;
}
</style>

<ul class="local-actions">
    <li><a href="<?= ssl_url('contributors/marker/0/') ?>" class="btn btn-primary">+ Create a marker</a></li>
</ul>

<?php if ($markers_count) { ?>
<h2>Your Markers</h2>
<table id="markers" class="table table-striped">
<thead>
<tr>
    <th>Enabled</th>
    <th>Starts</th>
    <th>Expires</th>
    <th>Category</th>
    <th>Title</th>
    <th>Content</th>
    <th>Edit</th>
</tr>
</thead>
<tbody>
<?php foreach ($markers as $marker) { ?>
<tr>
    <td><?= $marker->enabled ? 'Yes' : 'No' ?></td>
    <td><?= $marker->startdate ?></td>
    <td><?= $marker->expires ?></td>
    <td><?= htmlspecialchars($marker->category) ?></td>
    <td><?= htmlspecialchars($marker->title) ?></td>
    <td><?= htmlspecialchars(strip_tags(substr($marker->content,0,200))) ?></td>
    <td><a href="<?= ssl_url("contributors/marker/{$marker->id}") ?>">edit</a></td>
</tr>
<?php } ?>
</tbody>
</table>
<?php } ?>



<?php if ($this->loggedin['admin']) { ?>
<?php if ($other_markers_count) { ?>
<h2>Other Markers</h2>
<table id="other_markers" class="table table-striped">
<thead>
<tr>
    <th>Enabled</th>
    <th>Starts</th>
    <th>Expires</th>
    <th>Category</th>
    <th>Title</th>
    <th>Content</th>
    <th>Edit</th>
</tr>
</thead>
<tbody>
<?php foreach ($other_markers as $marker) { ?>
<tr>
    <td><?= $marker->enabled ? 'Yes' : 'No' ?></td>
    <td><?= $marker->startdate ?></td>
    <td><?= $marker->expires ?></td>
    <td><?= htmlspecialchars($marker->category) ?></td>
    <td><?= htmlspecialchars($marker->title) ?></td>
    <td><?= htmlspecialchars(strip_tags(substr($marker->content,0,200))) ?></td>
    <td><a href="<?= ssl_url("contributors/marker/{$marker->id}") ?>">edit</a></td>
</tr>
<?php } ?>
</tbody>
</table>
<?php } ?>
<?php } ?>



<script type="text/javascript">
$(window).load(function() { 
    $('#markers').tablesorter({ 
        sortList: [[1,0],[2,0]]
    });
    $('#markers').addClass('tablesorter');
}); 

$(window).load(function() { 
    $('#other_markers').tablesorter({ 
        sortList: [[1,0],[2,0]]
    });
    $('#other_markers').addClass('tablesorter');
}); 
</script>

<?php $this->load->view('contributors/footer.phtml') ?>
