<?php $this->page_title = 'Edit Marker'; ?>


<style type="text/css">
#map_canvas {
    width:5in; height:5in;
}

#ui-datepicker-div {
    display:none;
}

input.short {
    text-align:right;
    width:0.6in;
}

input.long {
    text-align:right;
    width:1.0in;
}

#deleteform {
    margin-top:1in;
    font-size:8pt;
}

textarea[name="content"] {
    width:2in;
    height:2in;
}

.ui-datepicker {
    /* a default z-index of 1 puts it below the map */
    z-index:200 !important;
}
</style>





<script type="text/javascript">
var MARKER;
var CENTER_MARKER_AFTER_GEOCODE;

$(window).load(function () {
/////
///// start the map
/////
initContributorMap();
var lat = <?= $marker ? $marker->lat : $this->config->item('geo_lat') ?>;
var lng = <?= $marker ? $marker->lng : $this->config->item('geo_lon') ?>;
var zum = <?= $marker ? 15 : 10 ?>;
MAP.setView(new L.LatLng(lat,lng),zum);


/////
///// add a draggable marker
///// the drag callback fills the lat & lon boxes, super simple
/////
CENTER_MARKER_AFTER_GEOCODE = MARKER = new L.Marker(new L.LatLng(lat,lng), { clickable:true, draggable:true });
MAP.addLayer(MARKER);
MARKER.on('drag', function (event) {
    var latlng = this.getLatLng();
    $('input[name="lat"]').val(latlng.lat);
    $('input[name="lng"]').val(latlng.lng);
});


/////
///// enable various buttons and clicks
/////

// left-click
// our version of a WMS GetFeatureInfo control: a map click calls query.php to get JSON info, and we construct a bubble
MAP.on('click', function (event) {
    var data = {};

    // buffer the click point a little to make a box
    var sw = MAP.layerPointToLatLng(new L.Point(event.layerPoint.x - 10 , event.layerPoint.y - 10));
    var ne = MAP.layerPointToLatLng(new L.Point(event.layerPoint.x + 10 , event.layerPoint.y + 10));
    data.w = sw.lng;
    data.s = sw.lat;
    data.e = ne.lng;
    data.n = ne.lat;
    data.zoom = MAP.getZoom();
    var anchor = new L.LatLng(event.latlng.lat,event.latlng.lng);

    // do the AJAX thing
    $.get('../../ajax/query', data, function (html) {
        if (!html) return;
        var popup = new L.Popup({ maxWidth:720, maxHeight:720 });
        popup.setLatLng(anchor);
        popup.setContent(html);
        MAP.openPopup(popup);

        var link = $('<span></span>').addClass('fakelink').text('Click here to place the marker here');
        link.click(function () {
            MARKER.setLatLng(anchor);
            $('input[name="lat"]').val(anchor.lat);
            $('input[name="lng"]').val(anchor.lng);
            MAP.closePopup();
        });
        $('.leaflet-popup-content').append(link);
    }, 'html');
});

// right-click
// move the marker here and update the text boxes
MAP.on('contextmenu', function (event) {
    var anchor = new L.LatLng(event.latlng.lat,event.latlng.lng);
    MARKER.setLatLng(event.latlng);
    $('input[name="lat"]').val(event.latlng.lat);
    $('input[name="lng"]').val(event.latlng.lng);
});


/////
///// enable the widgets for startdate and expiration date
/////

$('input[name="expires"]').datepicker({
    dateFormat: 'yy-mm-dd'
});

$('#expires_never').click(function () {
    $('input[name="expires"]').val('');
});

$('input[name="startdate"]').datepicker({
    dateFormat: 'yy-mm-dd'
});

$('#startdate_today').click(function () {
    var today = new Date().yyyymmdd();
    $('input[name="startdate"]').val(today);
});




/////
///// enable TinyMCE on the description editor
/////
$('textarea[name="content"]').tinymce({
    // Location of TinyMCE script
    script_url : '<?= ssl_url('static/tinymce/jscripts/tiny_mce/tiny_mce.js') ?>',

    // General options
    theme : "advanced",
    plugins : "autolink,lists,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,advlist",

    // Theme options
    theme_advanced_buttons1 : "cut,copy,paste,pastetext,pasteword,|,search,replace,|,undo,redo,|,hr,removeformat,|,charmap,emotions,media",
    theme_advanced_buttons2 : "code,|,bold,italic,underline,strikethrough,sub,sup,|,formatselect,fontselect,fontsizeselect",
    theme_advanced_buttons3 : "justifyleft,justifycenter,justifyright,justifyfull,|,bullist,numlist,|,outdent,indent,blockquote,|,link,unlink,anchor,image,|,forecolor,backcolor",
    theme_advanced_buttons4 : "tablecontrols",
    theme_advanced_toolbar_location : "top",
    theme_advanced_toolbar_align : "left",
    theme_advanced_statusbar_location : "bottom",
    theme_advanced_resizing : true,

    // Example content CSS (should be your site CSS)
    content_css : "css/content.css",

    // Drop lists for link/image/media/template dialogs
    template_external_list_url : "lists/template_list.js",
    external_link_list_url : "lists/link_list.js",
    external_image_list_url : "lists/image_list.js",
    media_external_list_url : "lists/media_list.js"
});



/////
///// END OF PAGE LOAD HANDLER
/////
});
</script>





<form id="loopform" method="post" action="<?= ssl_url("contributors/savemarker/") ?>">
<input type="hidden" name="id" value="<?= $marker ? $marker->id : 0 ?>" />

<table>
<tr>
    <td>Title:</td>
    <td><input class="form-control" type="text" name="title" maxlength="50" value="<?= $marker ? htmlspecialchars($marker->title) : '- Untitled Marker' ?>" /></td>
</tr>
<tr>
    <td>Category:</td>
    <td>
        <select class="form-control" name="category">
            <?php foreach ($categories as $category) { ?>
            <option <?= ($marker and $category == $marker->category) ? 'selected="true"' : '' ?> ><?= htmlspecialchars($category) ?></option>
            <?php } ?>
        </select>
    </td>
    <td>
    </td>
</tr>
<tr>
    <td>Start date:</td>
    <td>
        <input type="text" name="startdate" size="10" maxlength="10" value="<?= $marker ? $marker->startdate : date('Y-m-d') ?>" />
        <span class="btn btn-sm btn-default" id="startdate_today">today</span>
    </td>
    <td>
    </td>
</tr>
<tr>
    <td>Expiration date:</td>
    <td>
        <input type="text" name="expires" size="10" maxlength="10" value="<?= $marker ? $marker->expires : '' ?>" />
        <span class="btn btn-sm btn-default" id="expires_never">never</span>
        <br/>
        If this event expires, should it be re-enabled on the starting date the following year?<br/>
        <select class="form-control" name="annual">
            <option value="0" <?= ($marker and $marker->annual) ? '' : 'selected="true"' ?> >No, this marker will not repeat</option>
            <option value="1" <?= ($marker and $marker->annual) ? 'selected="true"' : '' ?> >Yes, re-enable this marker each year</option>
        </select>
    </td>
    <td>
    </td>
</tr>
<tr>
    <td>Location:</td>
    <td>
        <input type="text" name="lat" size="20" value="<?= $marker ? $marker->lat : $this->config->item('geo_lat') ?>" />
        <input type="text" name="lng" size="20" value="<?= $marker ? $marker->lng : $this->config->item('geo_lon') ?>" />
        <br/>
        <div id="map_canvas"></div>
    </td>
    <td>
        Click the map to get info. Right-click, or drag the marker, to place the marker.
        <br/>
        <br/>
        Your current GPS location:<br/>
        <input class="btn btn-default" type="button" id="gps_button" value="Go &gt;" />
        <br/>
        Search:<br/>
        <input type="text" id="cleocode_address" />
        <input class="btn btn-default" type="button" id="cleocode_button" value="Go &gt;" />
        <br/>
        <ul id="results"></ul>
    </td>
</tr>
<tr>
    <td>Popup content:</td>
    <td><textarea name="content"><?= $marker ? htmlspecialchars($marker->content) : '' ?></textarea></td>
    <td>
    </td>
</tr>
<tr>
    <td></td>
    <td>
        <input class="btn btn-primary" type="submit" value="Save Changes" />
    </td>
    <td>
    </td>
</tr>
</table>

</form>



<?php if ($marker) { ?>
<form id="deleteform" method="post" action="<?= ssl_url("contributors/deletemarker/") ?>" onSubmit="return confirm('Really delete this marker?');">
<input type="hidden" name="id" value="<?= $marker->id ?>" />
<input class="btn btn-primary" type="submit" value="Delete" />
</form>
<?php } ?>
