<?php $this->page_title = 'Change Password'; ?>

<form class="" id="editform" method="post" action="<?= ssl_current_url() ?>">

<div class="form-group">
<label>Enter your new password twice:</label>
<input class="form-control" type="password" name="password1" placeholder="New password" />
<input class="form-control" type="password" name="password2" placeholder="New password, again" />
</div>

<input class="btn btn-primary" type="submit" value="Submit" />

</form>


<script type="text/javascript">
var MY_EMAIL = <?= json_encode($this->loggedin['email']) ?>;

$(window).load(function() {
    $('#editform').submit(function () {
        var password1 = $('#editform input[name="password1"]').val()
        var password2 = $('#editform input[name="password2"]').val();

        // do the two passwords match?
        if (password1 != password2) { alert("The two entries do not match."); return false; }

        // are they blank?
        if (! password1) { alert("To cancel changing your password, use the top menu to leave the page."); return false; }

        // does it follow password guidelines?
        var error = null;
        if (password1.length < 8) error = "Passwords must be at least 8 characters.";
        if (! password1.match(/\d/)) error = "Passwords must contain at least one number.";
        if (password1.toLowerCase() == MY_EMAIL.toLowerCase() ) error = "Don't use your email address as your password.";
        if (error) { alert(error); return false; }

        // guess we're good!
        return true;
    });
});
</script>
