<?php
  $menu = array(
    array(
      'url' => 'docsnew/index/home',
      'title' => 'Home'
    ),
    array(
      'url' => 'docsnew/index/content',
      'title' => 'Content'
    ),
    array(
      'url' => 'docsnew/index/admin',
      'title' => 'Administration',
      'submenu' => array(
        array(
          'url' => 'docsnew/index/admin/users',
          'title' => 'Manage Users',
        ),
        array(
          'url' => 'docsnew/index/admin/data',
          'title' => 'Manage Data',
        ),
      ),
    ),
    array(
      'url' => 'docsnew/index/docs',
      'title' => 'Docs',
      'submenu' => array(
        array(
          'url' => 'docsnew/index/docs/content/panel',
          'title' => 'Content &amp; Contributors',
          'submenu' => array(
            array(
              'url' => 'docsnew/index/docs/content/panel',
              'title' => 'Content &amp; Contributors Panel',
            ),
          ),
        ),
        array(
          'url' => 'docsnew/index/docs/admin/panel',
          'title' => 'Administration',
          'submenu' => array(
            array(
              'url' => 'docsnew/index/docs/admin/panel',
              'title' => 'Admin Panel',
            ),
            array(
              'url' => 'docsnew/index/docs/admin/stack',
              'title' => 'Programming Language, Frameworks, Techniques',
            ),
            array(
              'url' => 'docsnew/index/docs/admin/js_compression',
              'title' => 'Javascript Compression',
            ),
            array(
              'url' => 'docsnew/index/docs/admin/mapfish_print',
              'title' => 'MapFish Print',
            ),
            array(
              'url' => 'docsnew/index/docs/admin/db_load',
              'title' => 'Database Load',
            ),
            array(
              'url' => 'docsnew/index/docs/admin/db_update',
              'title' => 'Database Update',
            ),
            array(
              'url' => 'docsnew/index/docs/admin/tilestache',
              'title' => 'TileStache Basemap',
            ),
          ),
        ),
        array(
          'url' => 'docsnew/index/docs/cms/cms',
          'title' => 'CMS &amp; Embedding',
          'submenu' => array(
            array(
              'url' => 'docsnew/index/docs/cms/cms',
              'title' => 'The CMS and embedded map pages',
            ),
            array(
              'url' => 'docsnew/index/docs/cms/finder',
              'title' => 'The Finders: embeddable search systems',
            ),
            array(
              'url' => 'docsnew/index/docs/cms/url_params',
              'title' => 'Controlling map start view',
            ),
          ),
        ),
      ),
    ),
    array(
      'url' => 'docsnew/index/testing',
      'title' => 'Testing'
    ),
  );
?>


<ul class="nav navbar-nav">
  <?php
    function print_menu($menu, $active_path='') {
      foreach ($menu as $item) {

        $classes = array();
        if (isset($item['url']) && $item['url'] == $active_path) {
          $classes[] = 'active';
        }
        if (isset($item['submenu'])) {
          $classes[] = 'dropdown';
        }

        $classes_str = ' class="';
        $i=0;
        foreach ($classes as $class) {
          $classes_str .= ($i++ > 0) ? ' ' : '';
          $classes_str .= $class;
        }
        $classes_str .= '"';

        print '<li' . $classes_str . '>';

        if (isset($item['submenu'])) {
          if (isset($item['url'])) {
            print '<a href="' . ssl_url($item['url']) . '" role="button" aria-haspopup="true" aria-expanded="true">' . $item['title'] . ' <span class="caret"></span></a>';
          } else {
            print '<a href="#" role="button" aria-haspopup="true" aria-expanded="true">' . $item['title'] . ' <span class="caret"></span></a>';
            //print $item['title'] . ' <span class="caret"></span></a>';
          }
          print '<ul class="dropdown-menu">';
          print_menu($item['submenu'], $active_path);
          print '</ul>';
        } else {
          print '<a href="' . ssl_url($item['url']) . '">' . $item['title'] . '</a>';
        }
        print '</li>' . "\n";
      }
    }
    print_menu($menu, $this->uri->uri_string);
  ?>
</ul>