<?php $this->page_title = 'Native App Releases'; ?>

<p class="lead">Development/testing releases for the native app</p>

<h2>iOS</h2>
<?php
    /**
     * Make iOS Releases list
     */

    // Get list of versions from CSV

    $ios_release_versions_file = $this->config->item('base_path') . '/static/native_dev/ios-release-versions.csv';
    $ios_versions = array();
    if (($handle = fopen($ios_release_versions_file, "r")) !== FALSE) {
        while (($data = fgetcsv($handle, 1000, ",")) !== FALSE) {
            $ios_versions[] = $data[0];
        }
        fclose($handle);
    }

    // Generate list markup
    $releases_dir_url = site_url('static/native_dev/ios') . '/';
    $list_markup = '<ul>';
    foreach($ios_versions as $version) {
        $manifest_url = 'itms-services://?action=download-manifest&url=' . $releases_dir_url . $version . '/manifest.plist';
        $install_link = '<a href="' . $manifest_url . '">' . $version . '</a>';
        $list_markup .= '<li>' . $install_link . '</li>';
    }
    $list_markup .= '</ul>';
    print $list_markup;
?>

<h2>Android</h2>

<p>From your Android device (where the Google account you’re signed-in to is on our testers list in Google Play Console), browse to <a href="https://play.google.com/apps/testing/com.clevelandmetroparks.cmapp">https://play.google.com/apps/testing/com.clevelandmetroparks.cmapp</a>.</p>

<p>That page should show the CM brand on top, and have some verbiage about the testing version. Click one of the links that say “download it on Google Play”. That should take you to the Play Store app, showing the new app.</p>

<p>From there you can install the app on your device.</p>