<?php $this->page_title = 'Admin Panel'; ?>

<h2>Admin Panel</h2>

<p>The admin panel is at <a target="_blank" href="<?= ssl_url('administration') ?>"><?= ssl_url('administration') ?></a> The username &amp; password are in <code>application/config/config.php</code> in plain text (edit this to change the login &amp; password). In   addition to the username and password, Google Re-CAPTCHA is used to prevent automated login attempts.</p>
<p>The admin panel requires the use of SSL (the https portion, instead of http) and you will be bounced over to the SSL version if you  try to use the non-SSL URL.</p>
<p>The admin panel is for administering several aspects of the system:</p>
<ul>
    <li><strong>Contributors</strong> -- People who are allowed to access the Contributors system to add Markers, etc.</li>
    <li><strong>TileStache Purge/Seed</strong></li>
    <li><strong>Log</strong> -- The activity audit log. Shows all use of admin and contributor privileges.</li>
</ul>

<h2>Contributors</h2>

<p>Contributor accounts are like assistant administrators. They can add Markers to the map, can tag trails as closed, and can manage   Loops. As such, it's important to limit who has access to these functions.</p>
<p>The <code>Contributors</code> sub-panel lists the existing Contributor accounts as well as what permissions they have. it also   provides self-explanatory options for creating, editing, and deleting Contributors.</p>
<p>
Contributors have the following yes/no permissions:<br/>
<ul>
    <li><strong>Markers</strong> -- The Contributor is allowed to add Markers.</li>
    <li><strong>SWGH</strong> -- In conjunction with Markers, they are allowed to add Markers with the category Health Tips.</li>
    <li><strong>Loops</strong> -- The Contributor is allowed to manage Loops.</li>
    <li><strike><strong>Closures</strong> -- The Contributor is allowed to manage Trail Closures.</strike></li>
</ul>
</p>

<h2>Audit Log</h2>

<p>This section is read-only. It lists audit-worthy activites that have taken place. This includes Contributors adding, editing, and deleting Markers, and the admin managing Contributor accounts.</p>