<?php $this->page_title = 'Controlling Map Start View'; ?>

<p class="lead">Controlling the map's starting view with URL parameters.</p>

<h2>Zooming to a specific Lat/Lon</h2>
<ul>
<li><b>lng</b> -- A decimal number. The longitude of the location to zoom.</li>
<li><b>lat</b> -- A decimal number. The latitude of the location to zoom.</li>
<li><b>zoom</b> -- An integer. The zoom level of the location to zoom. 11 is the minimum and shows the entire Cleveland region. 18 is the  maximum, and zooms tightly to a single building.</li>
</ul>
<p><a target="_blank" href="<?= site_url('/?zoom=15&amp;lng=-81.7141414&amp;lat=41.4479860') ?>">/?zoom=15&amp;lng=-81.7141414&amp;lat=41.4479860</a>
</p>

<!--
<h2>Zooming to a specific feature</h2>
<p>Note that this does not implicitly turn on other layers, so one can zoom to a Building and not have the Buildings layer visible. See   the <b>layers</b> parameter described above, if you need to ensure that a given layer is active.</p>
<ul>
<li><b>type</b> -- Any of: trail, building, poi, reservation, loop</li>
<li><b>name</b> -- The exact proper name of the thing being searched. This must match capitalization and punctuation.</li>
</ul>
<p>
  <a target="_blank" href="<?= site_url('/?type=reservation&amp;name=Huntington Reservation') ?>">/?type=reservation&amp;name=Huntington Reservation</a><br/>
  <a target="_blank" href="<?= site_url('/?type=building&amp;name=Harriet Keeler Picnic Shelter') ?>">/?type=building&amp;name=Harriet Keeler Picnic Shelter</a>
</p>
-->

<h2>Setting the basemap</h2>
<ul>
  <li><b>base</b> -- Any of: map, photo</li>
</ul>
<p><a target="_blank" href="<?= site_url('/?base=photo') ?>">/?base=photo</a></p>