<html>
<head>
    <meta charset="utf-8" />
    <title><?= htmlspecialchars($this->config->item('title')) ?> :: Documentation</title>

    <!-- our own local javaScript and CSS -->
    <link rel="stylesheet" type="text/css" href="<?= ssl_url('static/docs/docs.css'); ?>" />
</head>
<body>

<div id="header">
    <h1>Documentation</h1>
    <a href="<?= ssl_url('docs') ?>">Home</a>
</div>
