<?php $this->load->view('docs/header.phtml') ?>

<h3>Administration</h3>
<ul>
<li><a href="<?= ssl_url('docs/index/adminpanel') ?>">Administration Panel / Managing Contributors</a></li>
<li><a href="<?= ssl_url('docs/index/programmingbase') ?>">Programing Language, Frameworks, Techniques</a></li>
<li><a href="<?= ssl_url('docs/index/compression') ?>">JavaScript Compression</a></li>
<li><a href="<?= ssl_url('docs/index/mapfishprint') ?>">MapFish Print</a></li>
<li><a href="<?= ssl_url('docs/index/dbdata') ?>">Database Loading Process &amp; Notes</a></li>
<li><a href="<?= ssl_url('docs/index/updating_data') ?>">Database Patching: Uploading spreadsheets and replacing shapefiles</a></li>
<li><a href="<?= ssl_url('docs/index/tilestache') ?>">TileStache basemap</a></li>
</ul>

<h3>Contributors</h3>
<ul>
<li><a href="<?= ssl_url('docs/index/contributors') ?>">The Contributors Panel: A Guide for Contributors</a></li>
</ul>

<h3>CMS &amp; Embedding</h3>
<ul>
<li><a href="<?= ssl_url('docs/index/cms') ?>">The CMS and embedded map pages</a></li>
<li><a href="<?= ssl_url('docs/index/finder') ?>">The Finders: An Embeddable Set of Search Systems</a></li>
<li><a href="<?= ssl_url('docs/index/urlparams') ?>">Controlling the Desktop &amp; Mobile maps' starting view with URL parameters</a></li>
</ul>

<?php $this->load->view('docs/footer.phtml') ?>
